<?php
/**
 * BuyServiceSslCertificateRequestData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * BuyServiceSslCertificateRequestData Class Doc Comment
 *
 * @category Class
 * @description Details required to issue the SSL/TLS Certificate
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BuyServiceSslCertificateRequestData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'BuyServiceSslCertificateRequest_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'domain' => 'string',
        'approver_email' => 'string',
        'admin_role' => 'string',
        'admin_title' => 'string',
        'admin_first_name' => 'string',
        'admin_last_name' => 'string',
        'admin_email' => 'string',
        'admin_organization' => 'string',
        'admin_phone_cc' => 'string',
        'admin_phone_n' => 'string',
        'admin_address' => 'string',
        'admin_city' => 'string',
        'admin_state' => 'string',
        'admin_postcode' => 'string',
        'admin_country' => 'string',
        'csr' => 'string',
        'private_key' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'domain' => null,
        'approver_email' => 'email',
        'admin_role' => null,
        'admin_title' => null,
        'admin_first_name' => null,
        'admin_last_name' => null,
        'admin_email' => 'email',
        'admin_organization' => null,
        'admin_phone_cc' => null,
        'admin_phone_n' => null,
        'admin_address' => null,
        'admin_city' => null,
        'admin_state' => null,
        'admin_postcode' => null,
        'admin_country' => null,
        'csr' => null,
        'private_key' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'domain' => false,
        'approver_email' => false,
        'admin_role' => false,
        'admin_title' => false,
        'admin_first_name' => false,
        'admin_last_name' => false,
        'admin_email' => false,
        'admin_organization' => false,
        'admin_phone_cc' => false,
        'admin_phone_n' => false,
        'admin_address' => false,
        'admin_city' => false,
        'admin_state' => false,
        'admin_postcode' => false,
        'admin_country' => false,
        'csr' => true,
        'private_key' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'domain' => 'domain',
        'approver_email' => 'approver_email',
        'admin_role' => 'admin_role',
        'admin_title' => 'admin_title',
        'admin_first_name' => 'admin_first_name',
        'admin_last_name' => 'admin_last_name',
        'admin_email' => 'admin_email',
        'admin_organization' => 'admin_organization',
        'admin_phone_cc' => 'admin_phone_cc',
        'admin_phone_n' => 'admin_phone_n',
        'admin_address' => 'admin_address',
        'admin_city' => 'admin_city',
        'admin_state' => 'admin_state',
        'admin_postcode' => 'admin_postcode',
        'admin_country' => 'admin_country',
        'csr' => 'csr',
        'private_key' => 'private_key'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'domain' => 'setDomain',
        'approver_email' => 'setApproverEmail',
        'admin_role' => 'setAdminRole',
        'admin_title' => 'setAdminTitle',
        'admin_first_name' => 'setAdminFirstName',
        'admin_last_name' => 'setAdminLastName',
        'admin_email' => 'setAdminEmail',
        'admin_organization' => 'setAdminOrganization',
        'admin_phone_cc' => 'setAdminPhoneCc',
        'admin_phone_n' => 'setAdminPhoneN',
        'admin_address' => 'setAdminAddress',
        'admin_city' => 'setAdminCity',
        'admin_state' => 'setAdminState',
        'admin_postcode' => 'setAdminPostcode',
        'admin_country' => 'setAdminCountry',
        'csr' => 'setCsr',
        'private_key' => 'setPrivateKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'domain' => 'getDomain',
        'approver_email' => 'getApproverEmail',
        'admin_role' => 'getAdminRole',
        'admin_title' => 'getAdminTitle',
        'admin_first_name' => 'getAdminFirstName',
        'admin_last_name' => 'getAdminLastName',
        'admin_email' => 'getAdminEmail',
        'admin_organization' => 'getAdminOrganization',
        'admin_phone_cc' => 'getAdminPhoneCc',
        'admin_phone_n' => 'getAdminPhoneN',
        'admin_address' => 'getAdminAddress',
        'admin_city' => 'getAdminCity',
        'admin_state' => 'getAdminState',
        'admin_postcode' => 'getAdminPostcode',
        'admin_country' => 'getAdminCountry',
        'csr' => 'getCsr',
        'private_key' => 'getPrivateKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ADMIN_ROLE_BUSINESS_OWNER = 'Business Owner';
    public const ADMIN_ROLE_WEBSITE_OWNER = 'Website Owner';
    public const ADMIN_ROLE_PRESIDENT = 'President';
    public const ADMIN_ROLE_COMPANY_DIRECTOR = 'Company Director';
    public const ADMIN_TITLE_MRS = 'Mrs';
    public const ADMIN_TITLE_MR = 'Mr';
    public const ADMIN_TITLE_MISS = 'Miss';
    public const ADMIN_TITLE_MS = 'Ms';
    public const ADMIN_TITLE_DR = 'Dr';
    public const ADMIN_TITLE_REV = 'Rev';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAdminRoleAllowableValues()
    {
        return [
            self::ADMIN_ROLE_BUSINESS_OWNER,
            self::ADMIN_ROLE_WEBSITE_OWNER,
            self::ADMIN_ROLE_PRESIDENT,
            self::ADMIN_ROLE_COMPANY_DIRECTOR,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAdminTitleAllowableValues()
    {
        return [
            self::ADMIN_TITLE_MRS,
            self::ADMIN_TITLE_MR,
            self::ADMIN_TITLE_MISS,
            self::ADMIN_TITLE_MS,
            self::ADMIN_TITLE_DR,
            self::ADMIN_TITLE_REV,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('approver_email', $data ?? [], null);
        $this->setIfExists('admin_role', $data ?? [], null);
        $this->setIfExists('admin_title', $data ?? [], null);
        $this->setIfExists('admin_first_name', $data ?? [], null);
        $this->setIfExists('admin_last_name', $data ?? [], null);
        $this->setIfExists('admin_email', $data ?? [], null);
        $this->setIfExists('admin_organization', $data ?? [], null);
        $this->setIfExists('admin_phone_cc', $data ?? [], null);
        $this->setIfExists('admin_phone_n', $data ?? [], null);
        $this->setIfExists('admin_address', $data ?? [], null);
        $this->setIfExists('admin_city', $data ?? [], null);
        $this->setIfExists('admin_state', $data ?? [], null);
        $this->setIfExists('admin_postcode', $data ?? [], null);
        $this->setIfExists('admin_country', $data ?? [], null);
        $this->setIfExists('csr', $data ?? [], null);
        $this->setIfExists('private_key', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['approver_email'] === null) {
            $invalidProperties[] = "'approver_email' can't be null";
        }
        if ($this->container['admin_role'] === null) {
            $invalidProperties[] = "'admin_role' can't be null";
        }
        $allowedValues = $this->getAdminRoleAllowableValues();
        if (!is_null($this->container['admin_role']) && !in_array($this->container['admin_role'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'admin_role', must be one of '%s'",
                $this->container['admin_role'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['admin_title'] === null) {
            $invalidProperties[] = "'admin_title' can't be null";
        }
        $allowedValues = $this->getAdminTitleAllowableValues();
        if (!is_null($this->container['admin_title']) && !in_array($this->container['admin_title'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'admin_title', must be one of '%s'",
                $this->container['admin_title'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['admin_first_name'] === null) {
            $invalidProperties[] = "'admin_first_name' can't be null";
        }
        if ($this->container['admin_last_name'] === null) {
            $invalidProperties[] = "'admin_last_name' can't be null";
        }
        if ($this->container['admin_email'] === null) {
            $invalidProperties[] = "'admin_email' can't be null";
        }
        if ($this->container['admin_organization'] === null) {
            $invalidProperties[] = "'admin_organization' can't be null";
        }
        if ($this->container['admin_phone_cc'] === null) {
            $invalidProperties[] = "'admin_phone_cc' can't be null";
        }
        if ($this->container['admin_phone_n'] === null) {
            $invalidProperties[] = "'admin_phone_n' can't be null";
        }
        if ($this->container['admin_address'] === null) {
            $invalidProperties[] = "'admin_address' can't be null";
        }
        if ($this->container['admin_city'] === null) {
            $invalidProperties[] = "'admin_city' can't be null";
        }
        if ($this->container['admin_state'] === null) {
            $invalidProperties[] = "'admin_state' can't be null";
        }
        if ($this->container['admin_postcode'] === null) {
            $invalidProperties[] = "'admin_postcode' can't be null";
        }
        if ($this->container['admin_country'] === null) {
            $invalidProperties[] = "'admin_country' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain Main domain for the SSL Certificate
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets approver_email
     *
     * @return string
     */
    public function getApproverEmail()
    {
        return $this->container['approver_email'];
    }

    /**
     * Sets approver_email
     *
     * @param string $approver_email One of the email addresses accepted as \"approver\" email for the SSL Certificate validation
     *
     * @return self
     */
    public function setApproverEmail($approver_email)
    {
        if (is_null($approver_email)) {
            throw new \InvalidArgumentException('non-nullable approver_email cannot be null');
        }
        $this->container['approver_email'] = $approver_email;

        return $this;
    }

    /**
     * Gets admin_role
     *
     * @return string
     */
    public function getAdminRole()
    {
        return $this->container['admin_role'];
    }

    /**
     * Sets admin_role
     *
     * @param string $admin_role admin_role
     *
     * @return self
     */
    public function setAdminRole($admin_role)
    {
        if (is_null($admin_role)) {
            throw new \InvalidArgumentException('non-nullable admin_role cannot be null');
        }
        $allowedValues = $this->getAdminRoleAllowableValues();
        if (!in_array($admin_role, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'admin_role', must be one of '%s'",
                    $admin_role,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['admin_role'] = $admin_role;

        return $this;
    }

    /**
     * Gets admin_title
     *
     * @return string
     */
    public function getAdminTitle()
    {
        return $this->container['admin_title'];
    }

    /**
     * Sets admin_title
     *
     * @param string $admin_title admin_title
     *
     * @return self
     */
    public function setAdminTitle($admin_title)
    {
        if (is_null($admin_title)) {
            throw new \InvalidArgumentException('non-nullable admin_title cannot be null');
        }
        $allowedValues = $this->getAdminTitleAllowableValues();
        if (!in_array($admin_title, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'admin_title', must be one of '%s'",
                    $admin_title,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['admin_title'] = $admin_title;

        return $this;
    }

    /**
     * Gets admin_first_name
     *
     * @return string
     */
    public function getAdminFirstName()
    {
        return $this->container['admin_first_name'];
    }

    /**
     * Sets admin_first_name
     *
     * @param string $admin_first_name admin_first_name
     *
     * @return self
     */
    public function setAdminFirstName($admin_first_name)
    {
        if (is_null($admin_first_name)) {
            throw new \InvalidArgumentException('non-nullable admin_first_name cannot be null');
        }
        $this->container['admin_first_name'] = $admin_first_name;

        return $this;
    }

    /**
     * Gets admin_last_name
     *
     * @return string
     */
    public function getAdminLastName()
    {
        return $this->container['admin_last_name'];
    }

    /**
     * Sets admin_last_name
     *
     * @param string $admin_last_name admin_last_name
     *
     * @return self
     */
    public function setAdminLastName($admin_last_name)
    {
        if (is_null($admin_last_name)) {
            throw new \InvalidArgumentException('non-nullable admin_last_name cannot be null');
        }
        $this->container['admin_last_name'] = $admin_last_name;

        return $this;
    }

    /**
     * Gets admin_email
     *
     * @return string
     */
    public function getAdminEmail()
    {
        return $this->container['admin_email'];
    }

    /**
     * Sets admin_email
     *
     * @param string $admin_email admin_email
     *
     * @return self
     */
    public function setAdminEmail($admin_email)
    {
        if (is_null($admin_email)) {
            throw new \InvalidArgumentException('non-nullable admin_email cannot be null');
        }
        $this->container['admin_email'] = $admin_email;

        return $this;
    }

    /**
     * Gets admin_organization
     *
     * @return string
     */
    public function getAdminOrganization()
    {
        return $this->container['admin_organization'];
    }

    /**
     * Sets admin_organization
     *
     * @param string $admin_organization admin_organization
     *
     * @return self
     */
    public function setAdminOrganization($admin_organization)
    {
        if (is_null($admin_organization)) {
            throw new \InvalidArgumentException('non-nullable admin_organization cannot be null');
        }
        $this->container['admin_organization'] = $admin_organization;

        return $this;
    }

    /**
     * Gets admin_phone_cc
     *
     * @return string
     */
    public function getAdminPhoneCc()
    {
        return $this->container['admin_phone_cc'];
    }

    /**
     * Sets admin_phone_cc
     *
     * @param string $admin_phone_cc Country code phone prefix without leading \"0\" and without leading \"+\" sign; ie. \"44\" for UK or \"39\" for Italy
     *
     * @return self
     */
    public function setAdminPhoneCc($admin_phone_cc)
    {
        if (is_null($admin_phone_cc)) {
            throw new \InvalidArgumentException('non-nullable admin_phone_cc cannot be null');
        }
        $this->container['admin_phone_cc'] = $admin_phone_cc;

        return $this;
    }

    /**
     * Gets admin_phone_n
     *
     * @return string
     */
    public function getAdminPhoneN()
    {
        return $this->container['admin_phone_n'];
    }

    /**
     * Sets admin_phone_n
     *
     * @param string $admin_phone_n Phone number without country code phone prefix
     *
     * @return self
     */
    public function setAdminPhoneN($admin_phone_n)
    {
        if (is_null($admin_phone_n)) {
            throw new \InvalidArgumentException('non-nullable admin_phone_n cannot be null');
        }
        $this->container['admin_phone_n'] = $admin_phone_n;

        return $this;
    }

    /**
     * Gets admin_address
     *
     * @return string
     */
    public function getAdminAddress()
    {
        return $this->container['admin_address'];
    }

    /**
     * Sets admin_address
     *
     * @param string $admin_address admin_address
     *
     * @return self
     */
    public function setAdminAddress($admin_address)
    {
        if (is_null($admin_address)) {
            throw new \InvalidArgumentException('non-nullable admin_address cannot be null');
        }
        $this->container['admin_address'] = $admin_address;

        return $this;
    }

    /**
     * Gets admin_city
     *
     * @return string
     */
    public function getAdminCity()
    {
        return $this->container['admin_city'];
    }

    /**
     * Sets admin_city
     *
     * @param string $admin_city admin_city
     *
     * @return self
     */
    public function setAdminCity($admin_city)
    {
        if (is_null($admin_city)) {
            throw new \InvalidArgumentException('non-nullable admin_city cannot be null');
        }
        $this->container['admin_city'] = $admin_city;

        return $this;
    }

    /**
     * Gets admin_state
     *
     * @return string
     */
    public function getAdminState()
    {
        return $this->container['admin_state'];
    }

    /**
     * Sets admin_state
     *
     * @param string $admin_state State/Province
     *
     * @return self
     */
    public function setAdminState($admin_state)
    {
        if (is_null($admin_state)) {
            throw new \InvalidArgumentException('non-nullable admin_state cannot be null');
        }
        $this->container['admin_state'] = $admin_state;

        return $this;
    }

    /**
     * Gets admin_postcode
     *
     * @return string
     */
    public function getAdminPostcode()
    {
        return $this->container['admin_postcode'];
    }

    /**
     * Sets admin_postcode
     *
     * @param string $admin_postcode admin_postcode
     *
     * @return self
     */
    public function setAdminPostcode($admin_postcode)
    {
        if (is_null($admin_postcode)) {
            throw new \InvalidArgumentException('non-nullable admin_postcode cannot be null');
        }
        $this->container['admin_postcode'] = $admin_postcode;

        return $this;
    }

    /**
     * Gets admin_country
     *
     * @return string
     */
    public function getAdminCountry()
    {
        return $this->container['admin_country'];
    }

    /**
     * Sets admin_country
     *
     * @param string $admin_country ISO country code with 2 letters; ie. \"IT\" for Italy, \"ES\" for Spain
     *
     * @return self
     */
    public function setAdminCountry($admin_country)
    {
        if (is_null($admin_country)) {
            throw new \InvalidArgumentException('non-nullable admin_country cannot be null');
        }
        $this->container['admin_country'] = $admin_country;

        return $this;
    }

    /**
     * Gets csr
     *
     * @return string|null
     */
    public function getCsr()
    {
        return $this->container['csr'];
    }

    /**
     * Sets csr
     *
     * @param string|null $csr Use this only if you wish to provide your custom-generated CSR. If you specify your own generated CSR, you must provide the Private Key as well.
     *
     * @return self
     */
    public function setCsr($csr)
    {
        if (is_null($csr)) {
            array_push($this->openAPINullablesSetToNull, 'csr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csr', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csr'] = $csr;

        return $this;
    }

    /**
     * Gets private_key
     *
     * @return string|null
     */
    public function getPrivateKey()
    {
        return $this->container['private_key'];
    }

    /**
     * Sets private_key
     *
     * @param string|null $private_key Use this only if you wish to provide your custom-generated Private Key. If you specify your own generated Private Key, you must provide the CSR as well.
     *
     * @return self
     */
    public function setPrivateKey($private_key)
    {
        if (is_null($private_key)) {
            array_push($this->openAPINullablesSetToNull, 'private_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('private_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['private_key'] = $private_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


