<?php
/**
 * BuyServiceVeeamBaasRequestConfiguration
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * BuyServiceVeeamBaasRequestConfiguration Class Doc Comment
 *
 * @category Class
 * @description Veeam BaaS configuration options
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BuyServiceVeeamBaasRequestConfiguration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'BuyServiceVeeamBaasRequest_configuration';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'cloud_connect_gb' => 'int',
        'agent_server' => 'int',
        'agent_workstation' => 'int',
        'vbr_entplus_vm' => 'int',
        'vbr_entplus_server' => 'int',
        'vbr_entplus_workstation' => 'int',
        'vbr_entplus_gb' => 'int',
        'vbr_standard_vm' => 'int',
        'vbr_standard_server' => 'int',
        'vbr_standard_workstation' => 'int',
        'vb365_users' => 'int',
        'cc_license_vm' => 'int',
        'cc_license_server' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'cloud_connect_gb' => null,
        'agent_server' => null,
        'agent_workstation' => null,
        'vbr_entplus_vm' => null,
        'vbr_entplus_server' => null,
        'vbr_entplus_workstation' => null,
        'vbr_entplus_gb' => null,
        'vbr_standard_vm' => null,
        'vbr_standard_server' => null,
        'vbr_standard_workstation' => null,
        'vb365_users' => null,
        'cc_license_vm' => null,
        'cc_license_server' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'cloud_connect_gb' => false,
        'agent_server' => false,
        'agent_workstation' => false,
        'vbr_entplus_vm' => false,
        'vbr_entplus_server' => false,
        'vbr_entplus_workstation' => false,
        'vbr_entplus_gb' => false,
        'vbr_standard_vm' => false,
        'vbr_standard_server' => false,
        'vbr_standard_workstation' => false,
        'vb365_users' => false,
        'cc_license_vm' => false,
        'cc_license_server' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cloud_connect_gb' => 'cloud_connect_gb',
        'agent_server' => 'agent_server',
        'agent_workstation' => 'agent_workstation',
        'vbr_entplus_vm' => 'vbr_entplus_vm',
        'vbr_entplus_server' => 'vbr_entplus_server',
        'vbr_entplus_workstation' => 'vbr_entplus_workstation',
        'vbr_entplus_gb' => 'vbr_entplus_gb',
        'vbr_standard_vm' => 'vbr_standard_vm',
        'vbr_standard_server' => 'vbr_standard_server',
        'vbr_standard_workstation' => 'vbr_standard_workstation',
        'vb365_users' => 'vb365_users',
        'cc_license_vm' => 'cc_license_vm',
        'cc_license_server' => 'cc_license_server'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cloud_connect_gb' => 'setCloudConnectGb',
        'agent_server' => 'setAgentServer',
        'agent_workstation' => 'setAgentWorkstation',
        'vbr_entplus_vm' => 'setVbrEntplusVm',
        'vbr_entplus_server' => 'setVbrEntplusServer',
        'vbr_entplus_workstation' => 'setVbrEntplusWorkstation',
        'vbr_entplus_gb' => 'setVbrEntplusGb',
        'vbr_standard_vm' => 'setVbrStandardVm',
        'vbr_standard_server' => 'setVbrStandardServer',
        'vbr_standard_workstation' => 'setVbrStandardWorkstation',
        'vb365_users' => 'setVb365Users',
        'cc_license_vm' => 'setCcLicenseVm',
        'cc_license_server' => 'setCcLicenseServer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cloud_connect_gb' => 'getCloudConnectGb',
        'agent_server' => 'getAgentServer',
        'agent_workstation' => 'getAgentWorkstation',
        'vbr_entplus_vm' => 'getVbrEntplusVm',
        'vbr_entplus_server' => 'getVbrEntplusServer',
        'vbr_entplus_workstation' => 'getVbrEntplusWorkstation',
        'vbr_entplus_gb' => 'getVbrEntplusGb',
        'vbr_standard_vm' => 'getVbrStandardVm',
        'vbr_standard_server' => 'getVbrStandardServer',
        'vbr_standard_workstation' => 'getVbrStandardWorkstation',
        'vb365_users' => 'getVb365Users',
        'cc_license_vm' => 'getCcLicenseVm',
        'cc_license_server' => 'getCcLicenseServer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cloud_connect_gb', $data ?? [], null);
        $this->setIfExists('agent_server', $data ?? [], null);
        $this->setIfExists('agent_workstation', $data ?? [], null);
        $this->setIfExists('vbr_entplus_vm', $data ?? [], null);
        $this->setIfExists('vbr_entplus_server', $data ?? [], null);
        $this->setIfExists('vbr_entplus_workstation', $data ?? [], null);
        $this->setIfExists('vbr_entplus_gb', $data ?? [], null);
        $this->setIfExists('vbr_standard_vm', $data ?? [], null);
        $this->setIfExists('vbr_standard_server', $data ?? [], null);
        $this->setIfExists('vbr_standard_workstation', $data ?? [], null);
        $this->setIfExists('vb365_users', $data ?? [], null);
        $this->setIfExists('cc_license_vm', $data ?? [], null);
        $this->setIfExists('cc_license_server', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['vbr_entplus_gb']) && ($this->container['vbr_entplus_gb'] > 250)) {
            $invalidProperties[] = "invalid value for 'vbr_entplus_gb', must be smaller than or equal to 250.";
        }

        if (!is_null($this->container['vbr_entplus_gb']) && ($this->container['vbr_entplus_gb'] < 0)) {
            $invalidProperties[] = "invalid value for 'vbr_entplus_gb', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cloud_connect_gb
     *
     * @return int|null
     */
    public function getCloudConnectGb()
    {
        return $this->container['cloud_connect_gb'];
    }

    /**
     * Sets cloud_connect_gb
     *
     * @param int|null $cloud_connect_gb Veeam Cloud Connect storage: quantity (in GB) of storage.
     *
     * @return self
     */
    public function setCloudConnectGb($cloud_connect_gb)
    {
        if (is_null($cloud_connect_gb)) {
            throw new \InvalidArgumentException('non-nullable cloud_connect_gb cannot be null');
        }
        $this->container['cloud_connect_gb'] = $cloud_connect_gb;

        return $this;
    }

    /**
     * Gets agent_server
     *
     * @return int|null
     */
    public function getAgentServer()
    {
        return $this->container['agent_server'];
    }

    /**
     * Sets agent_server
     *
     * @param int|null $agent_server Veeam Agent: number of \"Server\" workloads.
     *
     * @return self
     */
    public function setAgentServer($agent_server)
    {
        if (is_null($agent_server)) {
            throw new \InvalidArgumentException('non-nullable agent_server cannot be null');
        }
        $this->container['agent_server'] = $agent_server;

        return $this;
    }

    /**
     * Gets agent_workstation
     *
     * @return int|null
     */
    public function getAgentWorkstation()
    {
        return $this->container['agent_workstation'];
    }

    /**
     * Sets agent_workstation
     *
     * @param int|null $agent_workstation Veeam Agent: number of \"Workstation\" workloads.
     *
     * @return self
     */
    public function setAgentWorkstation($agent_workstation)
    {
        if (is_null($agent_workstation)) {
            throw new \InvalidArgumentException('non-nullable agent_workstation cannot be null');
        }
        $this->container['agent_workstation'] = $agent_workstation;

        return $this;
    }

    /**
     * Gets vbr_entplus_vm
     *
     * @return int|null
     */
    public function getVbrEntplusVm()
    {
        return $this->container['vbr_entplus_vm'];
    }

    /**
     * Sets vbr_entplus_vm
     *
     * @param int|null $vbr_entplus_vm Veeam Backup & Replication (VBR) Enterprise Plus: number of \"VM in VMware/Hyper-V\" workloads.
     *
     * @return self
     */
    public function setVbrEntplusVm($vbr_entplus_vm)
    {
        if (is_null($vbr_entplus_vm)) {
            throw new \InvalidArgumentException('non-nullable vbr_entplus_vm cannot be null');
        }
        $this->container['vbr_entplus_vm'] = $vbr_entplus_vm;

        return $this;
    }

    /**
     * Gets vbr_entplus_server
     *
     * @return int|null
     */
    public function getVbrEntplusServer()
    {
        return $this->container['vbr_entplus_server'];
    }

    /**
     * Sets vbr_entplus_server
     *
     * @param int|null $vbr_entplus_server Veeam Backup & Replication (VBR) Enterprise Plus: number of \"Server\" workloads.
     *
     * @return self
     */
    public function setVbrEntplusServer($vbr_entplus_server)
    {
        if (is_null($vbr_entplus_server)) {
            throw new \InvalidArgumentException('non-nullable vbr_entplus_server cannot be null');
        }
        $this->container['vbr_entplus_server'] = $vbr_entplus_server;

        return $this;
    }

    /**
     * Gets vbr_entplus_workstation
     *
     * @return int|null
     */
    public function getVbrEntplusWorkstation()
    {
        return $this->container['vbr_entplus_workstation'];
    }

    /**
     * Sets vbr_entplus_workstation
     *
     * @param int|null $vbr_entplus_workstation Veeam Backup & Replication (VBR) Enterprise Plus: number of \"Workstation\" workloads.
     *
     * @return self
     */
    public function setVbrEntplusWorkstation($vbr_entplus_workstation)
    {
        if (is_null($vbr_entplus_workstation)) {
            throw new \InvalidArgumentException('non-nullable vbr_entplus_workstation cannot be null');
        }
        $this->container['vbr_entplus_workstation'] = $vbr_entplus_workstation;

        return $this;
    }

    /**
     * Gets vbr_entplus_gb
     *
     * @return int|null
     */
    public function getVbrEntplusGb()
    {
        return $this->container['vbr_entplus_gb'];
    }

    /**
     * Sets vbr_entplus_gb
     *
     * @param int|null $vbr_entplus_gb Veeam Backup & Replication (VBR) Enterprise Plus: number of slots for \"NAS\" workloads. Each slot represents 250 GB of storage.
     *
     * @return self
     */
    public function setVbrEntplusGb($vbr_entplus_gb)
    {
        if (is_null($vbr_entplus_gb)) {
            throw new \InvalidArgumentException('non-nullable vbr_entplus_gb cannot be null');
        }
        if (($vbr_entplus_gb > 250)) {
            throw new \InvalidArgumentException('invalid value for $vbr_entplus_gb when calling BuyServiceVeeamBaasRequestConfiguration., must be smaller than or equal to 250.');
        }
        if (($vbr_entplus_gb < 0)) {
            throw new \InvalidArgumentException('invalid value for $vbr_entplus_gb when calling BuyServiceVeeamBaasRequestConfiguration., must be bigger than or equal to 0.');
        }

        $this->container['vbr_entplus_gb'] = $vbr_entplus_gb;

        return $this;
    }

    /**
     * Gets vbr_standard_vm
     *
     * @return int|null
     */
    public function getVbrStandardVm()
    {
        return $this->container['vbr_standard_vm'];
    }

    /**
     * Sets vbr_standard_vm
     *
     * @param int|null $vbr_standard_vm Veeam Backup & Replication (VBR) Standard: number of \"VM in VMware/Hyper-V\" workloads.
     *
     * @return self
     */
    public function setVbrStandardVm($vbr_standard_vm)
    {
        if (is_null($vbr_standard_vm)) {
            throw new \InvalidArgumentException('non-nullable vbr_standard_vm cannot be null');
        }
        $this->container['vbr_standard_vm'] = $vbr_standard_vm;

        return $this;
    }

    /**
     * Gets vbr_standard_server
     *
     * @return int|null
     */
    public function getVbrStandardServer()
    {
        return $this->container['vbr_standard_server'];
    }

    /**
     * Sets vbr_standard_server
     *
     * @param int|null $vbr_standard_server Veeam Backup & Replication (VBR) Standard: number of \"Server\" workloads.
     *
     * @return self
     */
    public function setVbrStandardServer($vbr_standard_server)
    {
        if (is_null($vbr_standard_server)) {
            throw new \InvalidArgumentException('non-nullable vbr_standard_server cannot be null');
        }
        $this->container['vbr_standard_server'] = $vbr_standard_server;

        return $this;
    }

    /**
     * Gets vbr_standard_workstation
     *
     * @return int|null
     */
    public function getVbrStandardWorkstation()
    {
        return $this->container['vbr_standard_workstation'];
    }

    /**
     * Sets vbr_standard_workstation
     *
     * @param int|null $vbr_standard_workstation Veeam Backup & Replication (VBR) Standard: number of \"Workstation\" workloads.
     *
     * @return self
     */
    public function setVbrStandardWorkstation($vbr_standard_workstation)
    {
        if (is_null($vbr_standard_workstation)) {
            throw new \InvalidArgumentException('non-nullable vbr_standard_workstation cannot be null');
        }
        $this->container['vbr_standard_workstation'] = $vbr_standard_workstation;

        return $this;
    }

    /**
     * Gets vb365_users
     *
     * @return int|null
     */
    public function getVb365Users()
    {
        return $this->container['vb365_users'];
    }

    /**
     * Sets vb365_users
     *
     * @param int|null $vb365_users Veeam Backup for Microsoft 365: number of Users.
     *
     * @return self
     */
    public function setVb365Users($vb365_users)
    {
        if (is_null($vb365_users)) {
            throw new \InvalidArgumentException('non-nullable vb365_users cannot be null');
        }
        $this->container['vb365_users'] = $vb365_users;

        return $this;
    }

    /**
     * Gets cc_license_vm
     *
     * @return int|null
     */
    public function getCcLicenseVm()
    {
        return $this->container['cc_license_vm'];
    }

    /**
     * Sets cc_license_vm
     *
     * @param int|null $cc_license_vm Veeam Cloud Connect license: number of \"VM in VMware/Hyper-V\" workloads.
     *
     * @return self
     */
    public function setCcLicenseVm($cc_license_vm)
    {
        if (is_null($cc_license_vm)) {
            throw new \InvalidArgumentException('non-nullable cc_license_vm cannot be null');
        }
        $this->container['cc_license_vm'] = $cc_license_vm;

        return $this;
    }

    /**
     * Gets cc_license_server
     *
     * @return int|null
     */
    public function getCcLicenseServer()
    {
        return $this->container['cc_license_server'];
    }

    /**
     * Sets cc_license_server
     *
     * @param int|null $cc_license_server Veeam Cloud Connect license: number of \"Server\" workloads.
     *
     * @return self
     */
    public function setCcLicenseServer($cc_license_server)
    {
        if (is_null($cc_license_server)) {
            throw new \InvalidArgumentException('non-nullable cc_license_server cannot be null');
        }
        $this->container['cc_license_server'] = $cc_license_server;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


