<?php
/**
 * HostingCronjobCreateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * HostingCronjobCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HostingCronjobCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'HostingCronjobCreateRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'request_protocol' => 'string',
        'request_url' => 'string',
        'http_request_method' => 'string',
        'plan_month' => 'string',
        'plan_monthday' => 'string',
        'plan_weekday' => 'string',
        'plan_hour' => 'string',
        'plan_minute' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'request_protocol' => null,
        'request_url' => null,
        'http_request_method' => null,
        'plan_month' => null,
        'plan_monthday' => null,
        'plan_weekday' => null,
        'plan_hour' => null,
        'plan_minute' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'request_protocol' => false,
        'request_url' => false,
        'http_request_method' => false,
        'plan_month' => true,
        'plan_monthday' => true,
        'plan_weekday' => true,
        'plan_hour' => true,
        'plan_minute' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'request_protocol' => 'request_protocol',
        'request_url' => 'request_url',
        'http_request_method' => 'http_request_method',
        'plan_month' => 'plan_month',
        'plan_monthday' => 'plan_monthday',
        'plan_weekday' => 'plan_weekday',
        'plan_hour' => 'plan_hour',
        'plan_minute' => 'plan_minute'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'request_protocol' => 'setRequestProtocol',
        'request_url' => 'setRequestUrl',
        'http_request_method' => 'setHttpRequestMethod',
        'plan_month' => 'setPlanMonth',
        'plan_monthday' => 'setPlanMonthday',
        'plan_weekday' => 'setPlanWeekday',
        'plan_hour' => 'setPlanHour',
        'plan_minute' => 'setPlanMinute'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'request_protocol' => 'getRequestProtocol',
        'request_url' => 'getRequestUrl',
        'http_request_method' => 'getHttpRequestMethod',
        'plan_month' => 'getPlanMonth',
        'plan_monthday' => 'getPlanMonthday',
        'plan_weekday' => 'getPlanWeekday',
        'plan_hour' => 'getPlanHour',
        'plan_minute' => 'getPlanMinute'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('request_protocol', $data ?? [], null);
        $this->setIfExists('request_url', $data ?? [], null);
        $this->setIfExists('http_request_method', $data ?? [], 'GET');
        $this->setIfExists('plan_month', $data ?? [], null);
        $this->setIfExists('plan_monthday', $data ?? [], null);
        $this->setIfExists('plan_weekday', $data ?? [], null);
        $this->setIfExists('plan_hour', $data ?? [], null);
        $this->setIfExists('plan_minute', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets request_protocol
     *
     * @return string|null
     */
    public function getRequestProtocol()
    {
        return $this->container['request_protocol'];
    }

    /**
     * Sets request_protocol
     *
     * @param string|null $request_protocol http or https
     *
     * @return self
     */
    public function setRequestProtocol($request_protocol)
    {
        if (is_null($request_protocol)) {
            throw new \InvalidArgumentException('non-nullable request_protocol cannot be null');
        }
        $this->container['request_protocol'] = $request_protocol;

        return $this;
    }

    /**
     * Gets request_url
     *
     * @return string|null
     */
    public function getRequestUrl()
    {
        return $this->container['request_url'];
    }

    /**
     * Sets request_url
     *
     * @param string|null $request_url URL without protocol
     *
     * @return self
     */
    public function setRequestUrl($request_url)
    {
        if (is_null($request_url)) {
            throw new \InvalidArgumentException('non-nullable request_url cannot be null');
        }
        $this->container['request_url'] = $request_url;

        return $this;
    }

    /**
     * Gets http_request_method
     *
     * @return string|null
     */
    public function getHttpRequestMethod()
    {
        return $this->container['http_request_method'];
    }

    /**
     * Sets http_request_method
     *
     * @param string|null $http_request_method http_request_method
     *
     * @return self
     */
    public function setHttpRequestMethod($http_request_method)
    {
        if (is_null($http_request_method)) {
            throw new \InvalidArgumentException('non-nullable http_request_method cannot be null');
        }
        $this->container['http_request_method'] = $http_request_method;

        return $this;
    }

    /**
     * Gets plan_month
     *
     * @return string|null
     */
    public function getPlanMonth()
    {
        return $this->container['plan_month'];
    }

    /**
     * Sets plan_month
     *
     * @param string|null $plan_month plan_month
     *
     * @return self
     */
    public function setPlanMonth($plan_month)
    {
        if (is_null($plan_month)) {
            array_push($this->openAPINullablesSetToNull, 'plan_month');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan_month', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan_month'] = $plan_month;

        return $this;
    }

    /**
     * Gets plan_monthday
     *
     * @return string|null
     */
    public function getPlanMonthday()
    {
        return $this->container['plan_monthday'];
    }

    /**
     * Sets plan_monthday
     *
     * @param string|null $plan_monthday plan_monthday
     *
     * @return self
     */
    public function setPlanMonthday($plan_monthday)
    {
        if (is_null($plan_monthday)) {
            array_push($this->openAPINullablesSetToNull, 'plan_monthday');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan_monthday', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan_monthday'] = $plan_monthday;

        return $this;
    }

    /**
     * Gets plan_weekday
     *
     * @return string|null
     */
    public function getPlanWeekday()
    {
        return $this->container['plan_weekday'];
    }

    /**
     * Sets plan_weekday
     *
     * @param string|null $plan_weekday plan_weekday
     *
     * @return self
     */
    public function setPlanWeekday($plan_weekday)
    {
        if (is_null($plan_weekday)) {
            array_push($this->openAPINullablesSetToNull, 'plan_weekday');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan_weekday', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan_weekday'] = $plan_weekday;

        return $this;
    }

    /**
     * Gets plan_hour
     *
     * @return string|null
     */
    public function getPlanHour()
    {
        return $this->container['plan_hour'];
    }

    /**
     * Sets plan_hour
     *
     * @param string|null $plan_hour plan_hour
     *
     * @return self
     */
    public function setPlanHour($plan_hour)
    {
        if (is_null($plan_hour)) {
            array_push($this->openAPINullablesSetToNull, 'plan_hour');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan_hour', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan_hour'] = $plan_hour;

        return $this;
    }

    /**
     * Gets plan_minute
     *
     * @return string|null
     */
    public function getPlanMinute()
    {
        return $this->container['plan_minute'];
    }

    /**
     * Sets plan_minute
     *
     * @param string|null $plan_minute plan_minute
     *
     * @return self
     */
    public function setPlanMinute($plan_minute)
    {
        if (is_null($plan_minute)) {
            array_push($this->openAPINullablesSetToNull, 'plan_minute');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan_minute', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan_minute'] = $plan_minute;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


