<?php
/**
 * HostingModSecurity
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * HostingModSecurity Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HostingModSecurity implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'HostingModSecurity';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'hosting_id' => 'int',
        'is_available' => 'bool',
        'is_active' => 'bool',
        'firewall_compatible' => 'bool',
        'full_strict' => 'bool',
        'custom_rules' => 'string[]',
        'custom_set' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'hosting_id' => null,
        'is_available' => null,
        'is_active' => null,
        'firewall_compatible' => null,
        'full_strict' => null,
        'custom_rules' => null,
        'custom_set' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'hosting_id' => false,
        'is_available' => false,
        'is_active' => false,
        'firewall_compatible' => false,
        'full_strict' => true,
        'custom_rules' => true,
        'custom_set' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hosting_id' => 'hosting_id',
        'is_available' => 'is_available',
        'is_active' => 'is_active',
        'firewall_compatible' => 'firewall_compatible',
        'full_strict' => 'full_strict',
        'custom_rules' => 'custom_rules',
        'custom_set' => 'custom_set'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hosting_id' => 'setHostingId',
        'is_available' => 'setIsAvailable',
        'is_active' => 'setIsActive',
        'firewall_compatible' => 'setFirewallCompatible',
        'full_strict' => 'setFullStrict',
        'custom_rules' => 'setCustomRules',
        'custom_set' => 'setCustomSet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hosting_id' => 'getHostingId',
        'is_available' => 'getIsAvailable',
        'is_active' => 'getIsActive',
        'firewall_compatible' => 'getFirewallCompatible',
        'full_strict' => 'getFullStrict',
        'custom_rules' => 'getCustomRules',
        'custom_set' => 'getCustomSet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('hosting_id', $data ?? [], null);
        $this->setIfExists('is_available', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('firewall_compatible', $data ?? [], null);
        $this->setIfExists('full_strict', $data ?? [], null);
        $this->setIfExists('custom_rules', $data ?? [], null);
        $this->setIfExists('custom_set', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['hosting_id'] === null) {
            $invalidProperties[] = "'hosting_id' can't be null";
        }
        if ($this->container['is_available'] === null) {
            $invalidProperties[] = "'is_available' can't be null";
        }
        if ($this->container['is_active'] === null) {
            $invalidProperties[] = "'is_active' can't be null";
        }
        if ($this->container['firewall_compatible'] === null) {
            $invalidProperties[] = "'firewall_compatible' can't be null";
        }
        if ($this->container['full_strict'] === null && !$this->isNullableSetToNull('full_strict')) {
            $invalidProperties[] = "'full_strict' is required";
        }
        if ($this->container['custom_rules'] === null && !$this->isNullableSetToNull('custom_rules')) {
            $invalidProperties[] = "'custom_rules' is required";
        }
        if ($this->container['custom_set'] === null && !$this->isNullableSetToNull('custom_set')) {
            $invalidProperties[] = "'custom_set' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hosting_id
     *
     * @return int
     */
    public function getHostingId()
    {
        return $this->container['hosting_id'];
    }

    /**
     * Sets hosting_id
     *
     * @param int $hosting_id hosting_id
     *
     * @return self
     */
    public function setHostingId($hosting_id)
    {
        if (is_null($hosting_id)) {
            throw new \InvalidArgumentException('non-nullable hosting_id cannot be null');
        }
        $this->container['hosting_id'] = $hosting_id;

        return $this;
    }

    /**
     * Gets is_available
     *
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->container['is_available'];
    }

    /**
     * Sets is_available
     *
     * @param bool $is_available is_available
     *
     * @return self
     */
    public function setIsAvailable($is_available)
    {
        if (is_null($is_available)) {
            throw new \InvalidArgumentException('non-nullable is_available cannot be null');
        }
        $this->container['is_available'] = $is_available;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active is_active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets firewall_compatible
     *
     * @return bool
     */
    public function getFirewallCompatible()
    {
        return $this->container['firewall_compatible'];
    }

    /**
     * Sets firewall_compatible
     *
     * @param bool $firewall_compatible firewall_compatible
     *
     * @return self
     */
    public function setFirewallCompatible($firewall_compatible)
    {
        if (is_null($firewall_compatible)) {
            throw new \InvalidArgumentException('non-nullable firewall_compatible cannot be null');
        }
        $this->container['firewall_compatible'] = $firewall_compatible;

        return $this;
    }

    /**
     * Gets full_strict
     *
     * @return bool|null
     */
    public function getFullStrict()
    {
        return $this->container['full_strict'];
    }

    /**
     * Sets full_strict
     *
     * @param bool|null $full_strict full_strict
     *
     * @return self
     */
    public function setFullStrict($full_strict)
    {
        if (is_null($full_strict)) {
            array_push($this->openAPINullablesSetToNull, 'full_strict');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('full_strict', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['full_strict'] = $full_strict;

        return $this;
    }

    /**
     * Gets custom_rules
     *
     * @return string[]|null
     */
    public function getCustomRules()
    {
        return $this->container['custom_rules'];
    }

    /**
     * Sets custom_rules
     *
     * @param string[]|null $custom_rules custom_rules
     *
     * @return self
     */
    public function setCustomRules($custom_rules)
    {
        if (is_null($custom_rules)) {
            array_push($this->openAPINullablesSetToNull, 'custom_rules');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_rules', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_rules'] = $custom_rules;

        return $this;
    }

    /**
     * Gets custom_set
     *
     * @return string[]|null
     */
    public function getCustomSet()
    {
        return $this->container['custom_set'];
    }

    /**
     * Sets custom_set
     *
     * @param string[]|null $custom_set custom_set
     *
     * @return self
     */
    public function setCustomSet($custom_set)
    {
        if (is_null($custom_set)) {
            array_push($this->openAPINullablesSetToNull, 'custom_set');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_set', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_set'] = $custom_set;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


