<?php
/**
 * Microsoft365Tenant
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * Microsoft365Tenant Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Microsoft365Tenant implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Microsoft365Tenant';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'tenant_id' => 'int',
        'microsoft_uuid' => 'string',
        'domain_prefix' => 'string',
        'microsoft_domain' => 'string',
        'imported' => 'bool',
        'first_name' => 'string',
        'last_name' => 'string',
        'country' => 'string',
        'company_name' => 'string',
        'address' => 'string',
        'city' => 'string',
        'state' => 'string',
        'postal_code' => 'string',
        'email_address' => 'string',
        'phone_prefix' => 'string',
        'phone_number' => 'string',
        'locale' => 'string',
        'account_login' => 'string',
        'mca_compliant' => 'bool',
        'mca_sign_date' => '\DateTime',
        'mca_template_id' => 'string',
        'mca_error' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'tenant_id' => null,
        'microsoft_uuid' => null,
        'domain_prefix' => null,
        'microsoft_domain' => null,
        'imported' => null,
        'first_name' => null,
        'last_name' => null,
        'country' => null,
        'company_name' => null,
        'address' => null,
        'city' => null,
        'state' => null,
        'postal_code' => null,
        'email_address' => 'email',
        'phone_prefix' => null,
        'phone_number' => null,
        'locale' => null,
        'account_login' => null,
        'mca_compliant' => null,
        'mca_sign_date' => 'date-time',
        'mca_template_id' => null,
        'mca_error' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'tenant_id' => false,
        'microsoft_uuid' => true,
        'domain_prefix' => true,
        'microsoft_domain' => true,
        'imported' => false,
        'first_name' => true,
        'last_name' => true,
        'country' => true,
        'company_name' => true,
        'address' => true,
        'city' => true,
        'state' => true,
        'postal_code' => true,
        'email_address' => true,
        'phone_prefix' => true,
        'phone_number' => true,
        'locale' => true,
        'account_login' => true,
        'mca_compliant' => false,
        'mca_sign_date' => true,
        'mca_template_id' => true,
        'mca_error' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tenant_id' => 'tenant_id',
        'microsoft_uuid' => 'microsoft_uuid',
        'domain_prefix' => 'domain_prefix',
        'microsoft_domain' => 'microsoft_domain',
        'imported' => 'imported',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'country' => 'country',
        'company_name' => 'company_name',
        'address' => 'address',
        'city' => 'city',
        'state' => 'state',
        'postal_code' => 'postal_code',
        'email_address' => 'email_address',
        'phone_prefix' => 'phone_prefix',
        'phone_number' => 'phone_number',
        'locale' => 'locale',
        'account_login' => 'account_login',
        'mca_compliant' => 'mca_compliant',
        'mca_sign_date' => 'mca_sign_date',
        'mca_template_id' => 'mca_template_id',
        'mca_error' => 'mca_error'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tenant_id' => 'setTenantId',
        'microsoft_uuid' => 'setMicrosoftUuid',
        'domain_prefix' => 'setDomainPrefix',
        'microsoft_domain' => 'setMicrosoftDomain',
        'imported' => 'setImported',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'country' => 'setCountry',
        'company_name' => 'setCompanyName',
        'address' => 'setAddress',
        'city' => 'setCity',
        'state' => 'setState',
        'postal_code' => 'setPostalCode',
        'email_address' => 'setEmailAddress',
        'phone_prefix' => 'setPhonePrefix',
        'phone_number' => 'setPhoneNumber',
        'locale' => 'setLocale',
        'account_login' => 'setAccountLogin',
        'mca_compliant' => 'setMcaCompliant',
        'mca_sign_date' => 'setMcaSignDate',
        'mca_template_id' => 'setMcaTemplateId',
        'mca_error' => 'setMcaError'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tenant_id' => 'getTenantId',
        'microsoft_uuid' => 'getMicrosoftUuid',
        'domain_prefix' => 'getDomainPrefix',
        'microsoft_domain' => 'getMicrosoftDomain',
        'imported' => 'getImported',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'country' => 'getCountry',
        'company_name' => 'getCompanyName',
        'address' => 'getAddress',
        'city' => 'getCity',
        'state' => 'getState',
        'postal_code' => 'getPostalCode',
        'email_address' => 'getEmailAddress',
        'phone_prefix' => 'getPhonePrefix',
        'phone_number' => 'getPhoneNumber',
        'locale' => 'getLocale',
        'account_login' => 'getAccountLogin',
        'mca_compliant' => 'getMcaCompliant',
        'mca_sign_date' => 'getMcaSignDate',
        'mca_template_id' => 'getMcaTemplateId',
        'mca_error' => 'getMcaError'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('microsoft_uuid', $data ?? [], null);
        $this->setIfExists('domain_prefix', $data ?? [], null);
        $this->setIfExists('microsoft_domain', $data ?? [], null);
        $this->setIfExists('imported', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('company_name', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('postal_code', $data ?? [], null);
        $this->setIfExists('email_address', $data ?? [], null);
        $this->setIfExists('phone_prefix', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('account_login', $data ?? [], null);
        $this->setIfExists('mca_compliant', $data ?? [], null);
        $this->setIfExists('mca_sign_date', $data ?? [], null);
        $this->setIfExists('mca_template_id', $data ?? [], null);
        $this->setIfExists('mca_error', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets microsoft_uuid
     *
     * @return string|null
     */
    public function getMicrosoftUuid()
    {
        return $this->container['microsoft_uuid'];
    }

    /**
     * Sets microsoft_uuid
     *
     * @param string|null $microsoft_uuid microsoft_uuid
     *
     * @return self
     */
    public function setMicrosoftUuid($microsoft_uuid)
    {
        if (is_null($microsoft_uuid)) {
            array_push($this->openAPINullablesSetToNull, 'microsoft_uuid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('microsoft_uuid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['microsoft_uuid'] = $microsoft_uuid;

        return $this;
    }

    /**
     * Gets domain_prefix
     *
     * @return string|null
     */
    public function getDomainPrefix()
    {
        return $this->container['domain_prefix'];
    }

    /**
     * Sets domain_prefix
     *
     * @param string|null $domain_prefix domain_prefix
     *
     * @return self
     */
    public function setDomainPrefix($domain_prefix)
    {
        if (is_null($domain_prefix)) {
            array_push($this->openAPINullablesSetToNull, 'domain_prefix');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain_prefix', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain_prefix'] = $domain_prefix;

        return $this;
    }

    /**
     * Gets microsoft_domain
     *
     * @return string|null
     */
    public function getMicrosoftDomain()
    {
        return $this->container['microsoft_domain'];
    }

    /**
     * Sets microsoft_domain
     *
     * @param string|null $microsoft_domain microsoft_domain
     *
     * @return self
     */
    public function setMicrosoftDomain($microsoft_domain)
    {
        if (is_null($microsoft_domain)) {
            array_push($this->openAPINullablesSetToNull, 'microsoft_domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('microsoft_domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['microsoft_domain'] = $microsoft_domain;

        return $this;
    }

    /**
     * Gets imported
     *
     * @return bool|null
     */
    public function getImported()
    {
        return $this->container['imported'];
    }

    /**
     * Sets imported
     *
     * @param bool|null $imported imported
     *
     * @return self
     */
    public function setImported($imported)
    {
        if (is_null($imported)) {
            throw new \InvalidArgumentException('non-nullable imported cannot be null');
        }
        $this->container['imported'] = $imported;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            array_push($this->openAPINullablesSetToNull, 'first_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('first_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            array_push($this->openAPINullablesSetToNull, 'last_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets company_name
     *
     * @return string|null
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     *
     * @param string|null $company_name company_name
     *
     * @return self
     */
    public function setCompanyName($company_name)
    {
        if (is_null($company_name)) {
            array_push($this->openAPINullablesSetToNull, 'company_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('company_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            array_push($this->openAPINullablesSetToNull, 'address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            array_push($this->openAPINullablesSetToNull, 'city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string|null $postal_code postal_code
     *
     * @return self
     */
    public function setPostalCode($postal_code)
    {
        if (is_null($postal_code)) {
            array_push($this->openAPINullablesSetToNull, 'postal_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('postal_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets email_address
     *
     * @return string|null
     */
    public function getEmailAddress()
    {
        return $this->container['email_address'];
    }

    /**
     * Sets email_address
     *
     * @param string|null $email_address email_address
     *
     * @return self
     */
    public function setEmailAddress($email_address)
    {
        if (is_null($email_address)) {
            array_push($this->openAPINullablesSetToNull, 'email_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_address'] = $email_address;

        return $this;
    }

    /**
     * Gets phone_prefix
     *
     * @return string|null
     */
    public function getPhonePrefix()
    {
        return $this->container['phone_prefix'];
    }

    /**
     * Sets phone_prefix
     *
     * @param string|null $phone_prefix phone_prefix
     *
     * @return self
     */
    public function setPhonePrefix($phone_prefix)
    {
        if (is_null($phone_prefix)) {
            array_push($this->openAPINullablesSetToNull, 'phone_prefix');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_prefix', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_prefix'] = $phone_prefix;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string|null $phone_number phone_number
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            array_push($this->openAPINullablesSetToNull, 'locale');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locale', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets account_login
     *
     * @return string|null
     */
    public function getAccountLogin()
    {
        return $this->container['account_login'];
    }

    /**
     * Sets account_login
     *
     * @param string|null $account_login account_login
     *
     * @return self
     */
    public function setAccountLogin($account_login)
    {
        if (is_null($account_login)) {
            array_push($this->openAPINullablesSetToNull, 'account_login');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('account_login', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['account_login'] = $account_login;

        return $this;
    }

    /**
     * Gets mca_compliant
     *
     * @return bool|null
     */
    public function getMcaCompliant()
    {
        return $this->container['mca_compliant'];
    }

    /**
     * Sets mca_compliant
     *
     * @param bool|null $mca_compliant mca_compliant
     *
     * @return self
     */
    public function setMcaCompliant($mca_compliant)
    {
        if (is_null($mca_compliant)) {
            throw new \InvalidArgumentException('non-nullable mca_compliant cannot be null');
        }
        $this->container['mca_compliant'] = $mca_compliant;

        return $this;
    }

    /**
     * Gets mca_sign_date
     *
     * @return \DateTime|null
     */
    public function getMcaSignDate()
    {
        return $this->container['mca_sign_date'];
    }

    /**
     * Sets mca_sign_date
     *
     * @param \DateTime|null $mca_sign_date mca_sign_date
     *
     * @return self
     */
    public function setMcaSignDate($mca_sign_date)
    {
        if (is_null($mca_sign_date)) {
            array_push($this->openAPINullablesSetToNull, 'mca_sign_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mca_sign_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mca_sign_date'] = $mca_sign_date;

        return $this;
    }

    /**
     * Gets mca_template_id
     *
     * @return string|null
     */
    public function getMcaTemplateId()
    {
        return $this->container['mca_template_id'];
    }

    /**
     * Sets mca_template_id
     *
     * @param string|null $mca_template_id mca_template_id
     *
     * @return self
     */
    public function setMcaTemplateId($mca_template_id)
    {
        if (is_null($mca_template_id)) {
            array_push($this->openAPINullablesSetToNull, 'mca_template_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mca_template_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mca_template_id'] = $mca_template_id;

        return $this;
    }

    /**
     * Gets mca_error
     *
     * @return string|null
     */
    public function getMcaError()
    {
        return $this->container['mca_error'];
    }

    /**
     * Sets mca_error
     *
     * @param string|null $mca_error mca_error
     *
     * @return self
     */
    public function setMcaError($mca_error)
    {
        if (is_null($mca_error)) {
            array_push($this->openAPINullablesSetToNull, 'mca_error');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mca_error', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mca_error'] = $mca_error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


