<?php
/**
 * Microsoft365
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * Microsoft365 Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Microsoft365 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Microsoft365';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'microsoft365_id' => 'int',
        'purchase_id' => 'int',
        'tenant_id' => 'int',
        'service_name' => 'string',
        'purchase_name' => 'string',
        'supplier_code' => 'string',
        'supplier_status' => 'string',
        'order_code' => 'string',
        'order_reference' => 'string',
        'order_status' => 'string',
        'order_need_submit' => 'bool',
        'autorenew_enabled' => 'bool',
        'is_trial' => 'bool',
        'subscription_activation_date' => '\DateTime',
        'subscription_expiry_date' => '\DateTime',
        'tenant' => '\Shellrent\Sdk\Model\Microsoft365Tenant'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'microsoft365_id' => null,
        'purchase_id' => null,
        'tenant_id' => null,
        'service_name' => null,
        'purchase_name' => null,
        'supplier_code' => null,
        'supplier_status' => null,
        'order_code' => null,
        'order_reference' => null,
        'order_status' => null,
        'order_need_submit' => null,
        'autorenew_enabled' => null,
        'is_trial' => null,
        'subscription_activation_date' => 'date',
        'subscription_expiry_date' => 'date',
        'tenant' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'microsoft365_id' => false,
        'purchase_id' => false,
        'tenant_id' => true,
        'service_name' => true,
        'purchase_name' => true,
        'supplier_code' => true,
        'supplier_status' => true,
        'order_code' => true,
        'order_reference' => true,
        'order_status' => true,
        'order_need_submit' => false,
        'autorenew_enabled' => false,
        'is_trial' => false,
        'subscription_activation_date' => true,
        'subscription_expiry_date' => true,
        'tenant' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'microsoft365_id' => 'microsoft365_id',
        'purchase_id' => 'purchase_id',
        'tenant_id' => 'tenant_id',
        'service_name' => 'service_name',
        'purchase_name' => 'purchase_name',
        'supplier_code' => 'supplier_code',
        'supplier_status' => 'supplier_status',
        'order_code' => 'order_code',
        'order_reference' => 'order_reference',
        'order_status' => 'order_status',
        'order_need_submit' => 'order_need_submit',
        'autorenew_enabled' => 'autorenew_enabled',
        'is_trial' => 'is_trial',
        'subscription_activation_date' => 'subscription_activation_date',
        'subscription_expiry_date' => 'subscription_expiry_date',
        'tenant' => 'tenant'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'microsoft365_id' => 'setMicrosoft365Id',
        'purchase_id' => 'setPurchaseId',
        'tenant_id' => 'setTenantId',
        'service_name' => 'setServiceName',
        'purchase_name' => 'setPurchaseName',
        'supplier_code' => 'setSupplierCode',
        'supplier_status' => 'setSupplierStatus',
        'order_code' => 'setOrderCode',
        'order_reference' => 'setOrderReference',
        'order_status' => 'setOrderStatus',
        'order_need_submit' => 'setOrderNeedSubmit',
        'autorenew_enabled' => 'setAutorenewEnabled',
        'is_trial' => 'setIsTrial',
        'subscription_activation_date' => 'setSubscriptionActivationDate',
        'subscription_expiry_date' => 'setSubscriptionExpiryDate',
        'tenant' => 'setTenant'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'microsoft365_id' => 'getMicrosoft365Id',
        'purchase_id' => 'getPurchaseId',
        'tenant_id' => 'getTenantId',
        'service_name' => 'getServiceName',
        'purchase_name' => 'getPurchaseName',
        'supplier_code' => 'getSupplierCode',
        'supplier_status' => 'getSupplierStatus',
        'order_code' => 'getOrderCode',
        'order_reference' => 'getOrderReference',
        'order_status' => 'getOrderStatus',
        'order_need_submit' => 'getOrderNeedSubmit',
        'autorenew_enabled' => 'getAutorenewEnabled',
        'is_trial' => 'getIsTrial',
        'subscription_activation_date' => 'getSubscriptionActivationDate',
        'subscription_expiry_date' => 'getSubscriptionExpiryDate',
        'tenant' => 'getTenant'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('microsoft365_id', $data ?? [], null);
        $this->setIfExists('purchase_id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('purchase_name', $data ?? [], null);
        $this->setIfExists('supplier_code', $data ?? [], null);
        $this->setIfExists('supplier_status', $data ?? [], null);
        $this->setIfExists('order_code', $data ?? [], null);
        $this->setIfExists('order_reference', $data ?? [], null);
        $this->setIfExists('order_status', $data ?? [], null);
        $this->setIfExists('order_need_submit', $data ?? [], null);
        $this->setIfExists('autorenew_enabled', $data ?? [], null);
        $this->setIfExists('is_trial', $data ?? [], null);
        $this->setIfExists('subscription_activation_date', $data ?? [], null);
        $this->setIfExists('subscription_expiry_date', $data ?? [], null);
        $this->setIfExists('tenant', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets microsoft365_id
     *
     * @return int|null
     */
    public function getMicrosoft365Id()
    {
        return $this->container['microsoft365_id'];
    }

    /**
     * Sets microsoft365_id
     *
     * @param int|null $microsoft365_id microsoft365_id
     *
     * @return self
     */
    public function setMicrosoft365Id($microsoft365_id)
    {
        if (is_null($microsoft365_id)) {
            throw new \InvalidArgumentException('non-nullable microsoft365_id cannot be null');
        }
        $this->container['microsoft365_id'] = $microsoft365_id;

        return $this;
    }

    /**
     * Gets purchase_id
     *
     * @return int|null
     */
    public function getPurchaseId()
    {
        return $this->container['purchase_id'];
    }

    /**
     * Sets purchase_id
     *
     * @param int|null $purchase_id purchase_id
     *
     * @return self
     */
    public function setPurchaseId($purchase_id)
    {
        if (is_null($purchase_id)) {
            throw new \InvalidArgumentException('non-nullable purchase_id cannot be null');
        }
        $this->container['purchase_id'] = $purchase_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            array_push($this->openAPINullablesSetToNull, 'tenant_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name service_name
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            array_push($this->openAPINullablesSetToNull, 'service_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets purchase_name
     *
     * @return string|null
     */
    public function getPurchaseName()
    {
        return $this->container['purchase_name'];
    }

    /**
     * Sets purchase_name
     *
     * @param string|null $purchase_name purchase_name
     *
     * @return self
     */
    public function setPurchaseName($purchase_name)
    {
        if (is_null($purchase_name)) {
            array_push($this->openAPINullablesSetToNull, 'purchase_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchase_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchase_name'] = $purchase_name;

        return $this;
    }

    /**
     * Gets supplier_code
     *
     * @return string|null
     */
    public function getSupplierCode()
    {
        return $this->container['supplier_code'];
    }

    /**
     * Sets supplier_code
     *
     * @param string|null $supplier_code supplier_code
     *
     * @return self
     */
    public function setSupplierCode($supplier_code)
    {
        if (is_null($supplier_code)) {
            array_push($this->openAPINullablesSetToNull, 'supplier_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplier_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['supplier_code'] = $supplier_code;

        return $this;
    }

    /**
     * Gets supplier_status
     *
     * @return string|null
     */
    public function getSupplierStatus()
    {
        return $this->container['supplier_status'];
    }

    /**
     * Sets supplier_status
     *
     * @param string|null $supplier_status supplier_status
     *
     * @return self
     */
    public function setSupplierStatus($supplier_status)
    {
        if (is_null($supplier_status)) {
            array_push($this->openAPINullablesSetToNull, 'supplier_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplier_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['supplier_status'] = $supplier_status;

        return $this;
    }

    /**
     * Gets order_code
     *
     * @return string|null
     */
    public function getOrderCode()
    {
        return $this->container['order_code'];
    }

    /**
     * Sets order_code
     *
     * @param string|null $order_code order_code
     *
     * @return self
     */
    public function setOrderCode($order_code)
    {
        if (is_null($order_code)) {
            array_push($this->openAPINullablesSetToNull, 'order_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_code'] = $order_code;

        return $this;
    }

    /**
     * Gets order_reference
     *
     * @return string|null
     */
    public function getOrderReference()
    {
        return $this->container['order_reference'];
    }

    /**
     * Sets order_reference
     *
     * @param string|null $order_reference order_reference
     *
     * @return self
     */
    public function setOrderReference($order_reference)
    {
        if (is_null($order_reference)) {
            array_push($this->openAPINullablesSetToNull, 'order_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_reference'] = $order_reference;

        return $this;
    }

    /**
     * Gets order_status
     *
     * @return string|null
     */
    public function getOrderStatus()
    {
        return $this->container['order_status'];
    }

    /**
     * Sets order_status
     *
     * @param string|null $order_status order_status
     *
     * @return self
     */
    public function setOrderStatus($order_status)
    {
        if (is_null($order_status)) {
            array_push($this->openAPINullablesSetToNull, 'order_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_status'] = $order_status;

        return $this;
    }

    /**
     * Gets order_need_submit
     *
     * @return bool|null
     */
    public function getOrderNeedSubmit()
    {
        return $this->container['order_need_submit'];
    }

    /**
     * Sets order_need_submit
     *
     * @param bool|null $order_need_submit order_need_submit
     *
     * @return self
     */
    public function setOrderNeedSubmit($order_need_submit)
    {
        if (is_null($order_need_submit)) {
            throw new \InvalidArgumentException('non-nullable order_need_submit cannot be null');
        }
        $this->container['order_need_submit'] = $order_need_submit;

        return $this;
    }

    /**
     * Gets autorenew_enabled
     *
     * @return bool|null
     */
    public function getAutorenewEnabled()
    {
        return $this->container['autorenew_enabled'];
    }

    /**
     * Sets autorenew_enabled
     *
     * @param bool|null $autorenew_enabled autorenew_enabled
     *
     * @return self
     */
    public function setAutorenewEnabled($autorenew_enabled)
    {
        if (is_null($autorenew_enabled)) {
            throw new \InvalidArgumentException('non-nullable autorenew_enabled cannot be null');
        }
        $this->container['autorenew_enabled'] = $autorenew_enabled;

        return $this;
    }

    /**
     * Gets is_trial
     *
     * @return bool|null
     */
    public function getIsTrial()
    {
        return $this->container['is_trial'];
    }

    /**
     * Sets is_trial
     *
     * @param bool|null $is_trial is_trial
     *
     * @return self
     */
    public function setIsTrial($is_trial)
    {
        if (is_null($is_trial)) {
            throw new \InvalidArgumentException('non-nullable is_trial cannot be null');
        }
        $this->container['is_trial'] = $is_trial;

        return $this;
    }

    /**
     * Gets subscription_activation_date
     *
     * @return \DateTime|null
     */
    public function getSubscriptionActivationDate()
    {
        return $this->container['subscription_activation_date'];
    }

    /**
     * Sets subscription_activation_date
     *
     * @param \DateTime|null $subscription_activation_date subscription_activation_date
     *
     * @return self
     */
    public function setSubscriptionActivationDate($subscription_activation_date)
    {
        if (is_null($subscription_activation_date)) {
            array_push($this->openAPINullablesSetToNull, 'subscription_activation_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscription_activation_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscription_activation_date'] = $subscription_activation_date;

        return $this;
    }

    /**
     * Gets subscription_expiry_date
     *
     * @return \DateTime|null
     */
    public function getSubscriptionExpiryDate()
    {
        return $this->container['subscription_expiry_date'];
    }

    /**
     * Sets subscription_expiry_date
     *
     * @param \DateTime|null $subscription_expiry_date subscription_expiry_date
     *
     * @return self
     */
    public function setSubscriptionExpiryDate($subscription_expiry_date)
    {
        if (is_null($subscription_expiry_date)) {
            array_push($this->openAPINullablesSetToNull, 'subscription_expiry_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscription_expiry_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscription_expiry_date'] = $subscription_expiry_date;

        return $this;
    }

    /**
     * Gets tenant
     *
     * @return \Shellrent\Sdk\Model\Microsoft365Tenant|null
     */
    public function getTenant()
    {
        return $this->container['tenant'];
    }

    /**
     * Sets tenant
     *
     * @param \Shellrent\Sdk\Model\Microsoft365Tenant|null $tenant tenant
     *
     * @return self
     */
    public function setTenant($tenant)
    {
        if (is_null($tenant)) {
            array_push($this->openAPINullablesSetToNull, 'tenant');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant'] = $tenant;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


