<?php
/**
 * ObjectStorageIamUser
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * ObjectStorageIamUser Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ObjectStorageIamUser implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ObjectStorageIamUser';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'iam_user_id' => 'int',
        'object_storage_id' => 'int',
        'sub_account_id' => 'int',
        'code' => 'string',
        'code_full' => 'string',
        'iam_id' => 'string',
        'arn' => 'string',
        'active' => 'bool',
        'firewall_policy' => 'string',
        'date_created' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'iam_user_id' => null,
        'object_storage_id' => null,
        'sub_account_id' => null,
        'code' => null,
        'code_full' => null,
        'iam_id' => null,
        'arn' => null,
        'active' => null,
        'firewall_policy' => null,
        'date_created' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'iam_user_id' => false,
        'object_storage_id' => false,
        'sub_account_id' => false,
        'code' => true,
        'code_full' => true,
        'iam_id' => true,
        'arn' => true,
        'active' => true,
        'firewall_policy' => true,
        'date_created' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'iam_user_id' => 'iam_user_id',
        'object_storage_id' => 'object_storage_id',
        'sub_account_id' => 'sub_account_id',
        'code' => 'code',
        'code_full' => 'code_full',
        'iam_id' => 'iam_id',
        'arn' => 'arn',
        'active' => 'active',
        'firewall_policy' => 'firewall_policy',
        'date_created' => 'date_created'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'iam_user_id' => 'setIamUserId',
        'object_storage_id' => 'setObjectStorageId',
        'sub_account_id' => 'setSubAccountId',
        'code' => 'setCode',
        'code_full' => 'setCodeFull',
        'iam_id' => 'setIamId',
        'arn' => 'setArn',
        'active' => 'setActive',
        'firewall_policy' => 'setFirewallPolicy',
        'date_created' => 'setDateCreated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'iam_user_id' => 'getIamUserId',
        'object_storage_id' => 'getObjectStorageId',
        'sub_account_id' => 'getSubAccountId',
        'code' => 'getCode',
        'code_full' => 'getCodeFull',
        'iam_id' => 'getIamId',
        'arn' => 'getArn',
        'active' => 'getActive',
        'firewall_policy' => 'getFirewallPolicy',
        'date_created' => 'getDateCreated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('iam_user_id', $data ?? [], null);
        $this->setIfExists('object_storage_id', $data ?? [], null);
        $this->setIfExists('sub_account_id', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('code_full', $data ?? [], null);
        $this->setIfExists('iam_id', $data ?? [], null);
        $this->setIfExists('arn', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('firewall_policy', $data ?? [], null);
        $this->setIfExists('date_created', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets iam_user_id
     *
     * @return int|null
     */
    public function getIamUserId()
    {
        return $this->container['iam_user_id'];
    }

    /**
     * Sets iam_user_id
     *
     * @param int|null $iam_user_id iam_user_id
     *
     * @return self
     */
    public function setIamUserId($iam_user_id)
    {
        if (is_null($iam_user_id)) {
            throw new \InvalidArgumentException('non-nullable iam_user_id cannot be null');
        }
        $this->container['iam_user_id'] = $iam_user_id;

        return $this;
    }

    /**
     * Gets object_storage_id
     *
     * @return int|null
     */
    public function getObjectStorageId()
    {
        return $this->container['object_storage_id'];
    }

    /**
     * Sets object_storage_id
     *
     * @param int|null $object_storage_id object_storage_id
     *
     * @return self
     */
    public function setObjectStorageId($object_storage_id)
    {
        if (is_null($object_storage_id)) {
            throw new \InvalidArgumentException('non-nullable object_storage_id cannot be null');
        }
        $this->container['object_storage_id'] = $object_storage_id;

        return $this;
    }

    /**
     * Gets sub_account_id
     *
     * @return int|null
     */
    public function getSubAccountId()
    {
        return $this->container['sub_account_id'];
    }

    /**
     * Sets sub_account_id
     *
     * @param int|null $sub_account_id sub_account_id
     *
     * @return self
     */
    public function setSubAccountId($sub_account_id)
    {
        if (is_null($sub_account_id)) {
            throw new \InvalidArgumentException('non-nullable sub_account_id cannot be null');
        }
        $this->container['sub_account_id'] = $sub_account_id;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            array_push($this->openAPINullablesSetToNull, 'code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets code_full
     *
     * @return string|null
     */
    public function getCodeFull()
    {
        return $this->container['code_full'];
    }

    /**
     * Sets code_full
     *
     * @param string|null $code_full code_full
     *
     * @return self
     */
    public function setCodeFull($code_full)
    {
        if (is_null($code_full)) {
            array_push($this->openAPINullablesSetToNull, 'code_full');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('code_full', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['code_full'] = $code_full;

        return $this;
    }

    /**
     * Gets iam_id
     *
     * @return string|null
     */
    public function getIamId()
    {
        return $this->container['iam_id'];
    }

    /**
     * Sets iam_id
     *
     * @param string|null $iam_id iam_id
     *
     * @return self
     */
    public function setIamId($iam_id)
    {
        if (is_null($iam_id)) {
            array_push($this->openAPINullablesSetToNull, 'iam_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('iam_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['iam_id'] = $iam_id;

        return $this;
    }

    /**
     * Gets arn
     *
     * @return string|null
     */
    public function getArn()
    {
        return $this->container['arn'];
    }

    /**
     * Sets arn
     *
     * @param string|null $arn arn
     *
     * @return self
     */
    public function setArn($arn)
    {
        if (is_null($arn)) {
            array_push($this->openAPINullablesSetToNull, 'arn');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('arn', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['arn'] = $arn;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        if (is_null($active)) {
            array_push($this->openAPINullablesSetToNull, 'active');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets firewall_policy
     *
     * @return string|null
     */
    public function getFirewallPolicy()
    {
        return $this->container['firewall_policy'];
    }

    /**
     * Sets firewall_policy
     *
     * @param string|null $firewall_policy firewall_policy
     *
     * @return self
     */
    public function setFirewallPolicy($firewall_policy)
    {
        if (is_null($firewall_policy)) {
            array_push($this->openAPINullablesSetToNull, 'firewall_policy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('firewall_policy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['firewall_policy'] = $firewall_policy;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return \DateTime|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param \DateTime|null $date_created date_created
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            array_push($this->openAPINullablesSetToNull, 'date_created');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_created', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


