<?php
/**
 * Recurrence
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * Recurrence Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Recurrence implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Recurrence';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'recurrence_id' => 'int',
        'frequency' => '\Shellrent\Sdk\Model\RecurrenceFrequency',
        'days_renew' => 'int',
        'days_autorenew' => 'int',
        'days_suspension' => 'int',
        'days_restore' => 'int',
        'days_dismission' => 'int',
        'days_cancel' => 'int',
        'days_renew_dismission' => 'int',
        'days_no_secondary' => 'int',
        'days_no_service_change' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'recurrence_id' => null,
        'frequency' => null,
        'days_renew' => null,
        'days_autorenew' => null,
        'days_suspension' => null,
        'days_restore' => null,
        'days_dismission' => null,
        'days_cancel' => null,
        'days_renew_dismission' => null,
        'days_no_secondary' => null,
        'days_no_service_change' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'recurrence_id' => false,
        'frequency' => false,
        'days_renew' => true,
        'days_autorenew' => true,
        'days_suspension' => true,
        'days_restore' => true,
        'days_dismission' => true,
        'days_cancel' => false,
        'days_renew_dismission' => true,
        'days_no_secondary' => true,
        'days_no_service_change' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'recurrence_id' => 'recurrence_id',
        'frequency' => 'frequency',
        'days_renew' => 'days_renew',
        'days_autorenew' => 'days_autorenew',
        'days_suspension' => 'days_suspension',
        'days_restore' => 'days_restore',
        'days_dismission' => 'days_dismission',
        'days_cancel' => 'days_cancel',
        'days_renew_dismission' => 'days_renew_dismission',
        'days_no_secondary' => 'days_no_secondary',
        'days_no_service_change' => 'days_no_service_change'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'recurrence_id' => 'setRecurrenceId',
        'frequency' => 'setFrequency',
        'days_renew' => 'setDaysRenew',
        'days_autorenew' => 'setDaysAutorenew',
        'days_suspension' => 'setDaysSuspension',
        'days_restore' => 'setDaysRestore',
        'days_dismission' => 'setDaysDismission',
        'days_cancel' => 'setDaysCancel',
        'days_renew_dismission' => 'setDaysRenewDismission',
        'days_no_secondary' => 'setDaysNoSecondary',
        'days_no_service_change' => 'setDaysNoServiceChange'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'recurrence_id' => 'getRecurrenceId',
        'frequency' => 'getFrequency',
        'days_renew' => 'getDaysRenew',
        'days_autorenew' => 'getDaysAutorenew',
        'days_suspension' => 'getDaysSuspension',
        'days_restore' => 'getDaysRestore',
        'days_dismission' => 'getDaysDismission',
        'days_cancel' => 'getDaysCancel',
        'days_renew_dismission' => 'getDaysRenewDismission',
        'days_no_secondary' => 'getDaysNoSecondary',
        'days_no_service_change' => 'getDaysNoServiceChange'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('recurrence_id', $data ?? [], null);
        $this->setIfExists('frequency', $data ?? [], null);
        $this->setIfExists('days_renew', $data ?? [], null);
        $this->setIfExists('days_autorenew', $data ?? [], null);
        $this->setIfExists('days_suspension', $data ?? [], null);
        $this->setIfExists('days_restore', $data ?? [], null);
        $this->setIfExists('days_dismission', $data ?? [], null);
        $this->setIfExists('days_cancel', $data ?? [], null);
        $this->setIfExists('days_renew_dismission', $data ?? [], null);
        $this->setIfExists('days_no_secondary', $data ?? [], null);
        $this->setIfExists('days_no_service_change', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets recurrence_id
     *
     * @return int|null
     */
    public function getRecurrenceId()
    {
        return $this->container['recurrence_id'];
    }

    /**
     * Sets recurrence_id
     *
     * @param int|null $recurrence_id recurrence_id
     *
     * @return self
     */
    public function setRecurrenceId($recurrence_id)
    {
        if (is_null($recurrence_id)) {
            throw new \InvalidArgumentException('non-nullable recurrence_id cannot be null');
        }
        $this->container['recurrence_id'] = $recurrence_id;

        return $this;
    }

    /**
     * Gets frequency
     *
     * @return \Shellrent\Sdk\Model\RecurrenceFrequency|null
     */
    public function getFrequency()
    {
        return $this->container['frequency'];
    }

    /**
     * Sets frequency
     *
     * @param \Shellrent\Sdk\Model\RecurrenceFrequency|null $frequency frequency
     *
     * @return self
     */
    public function setFrequency($frequency)
    {
        if (is_null($frequency)) {
            throw new \InvalidArgumentException('non-nullable frequency cannot be null');
        }
        $this->container['frequency'] = $frequency;

        return $this;
    }

    /**
     * Gets days_renew
     *
     * @return int|null
     */
    public function getDaysRenew()
    {
        return $this->container['days_renew'];
    }

    /**
     * Sets days_renew
     *
     * @param int|null $days_renew days_renew
     *
     * @return self
     */
    public function setDaysRenew($days_renew)
    {
        if (is_null($days_renew)) {
            array_push($this->openAPINullablesSetToNull, 'days_renew');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_renew', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_renew'] = $days_renew;

        return $this;
    }

    /**
     * Gets days_autorenew
     *
     * @return int|null
     */
    public function getDaysAutorenew()
    {
        return $this->container['days_autorenew'];
    }

    /**
     * Sets days_autorenew
     *
     * @param int|null $days_autorenew days_autorenew
     *
     * @return self
     */
    public function setDaysAutorenew($days_autorenew)
    {
        if (is_null($days_autorenew)) {
            array_push($this->openAPINullablesSetToNull, 'days_autorenew');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_autorenew', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_autorenew'] = $days_autorenew;

        return $this;
    }

    /**
     * Gets days_suspension
     *
     * @return int|null
     */
    public function getDaysSuspension()
    {
        return $this->container['days_suspension'];
    }

    /**
     * Sets days_suspension
     *
     * @param int|null $days_suspension days_suspension
     *
     * @return self
     */
    public function setDaysSuspension($days_suspension)
    {
        if (is_null($days_suspension)) {
            array_push($this->openAPINullablesSetToNull, 'days_suspension');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_suspension', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_suspension'] = $days_suspension;

        return $this;
    }

    /**
     * Gets days_restore
     *
     * @return int|null
     */
    public function getDaysRestore()
    {
        return $this->container['days_restore'];
    }

    /**
     * Sets days_restore
     *
     * @param int|null $days_restore days_restore
     *
     * @return self
     */
    public function setDaysRestore($days_restore)
    {
        if (is_null($days_restore)) {
            array_push($this->openAPINullablesSetToNull, 'days_restore');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_restore', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_restore'] = $days_restore;

        return $this;
    }

    /**
     * Gets days_dismission
     *
     * @return int|null
     */
    public function getDaysDismission()
    {
        return $this->container['days_dismission'];
    }

    /**
     * Sets days_dismission
     *
     * @param int|null $days_dismission days_dismission
     *
     * @return self
     */
    public function setDaysDismission($days_dismission)
    {
        if (is_null($days_dismission)) {
            array_push($this->openAPINullablesSetToNull, 'days_dismission');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_dismission', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_dismission'] = $days_dismission;

        return $this;
    }

    /**
     * Gets days_cancel
     *
     * @return int|null
     */
    public function getDaysCancel()
    {
        return $this->container['days_cancel'];
    }

    /**
     * Sets days_cancel
     *
     * @param int|null $days_cancel days_cancel
     *
     * @return self
     */
    public function setDaysCancel($days_cancel)
    {
        if (is_null($days_cancel)) {
            throw new \InvalidArgumentException('non-nullable days_cancel cannot be null');
        }
        $this->container['days_cancel'] = $days_cancel;

        return $this;
    }

    /**
     * Gets days_renew_dismission
     *
     * @return int|null
     */
    public function getDaysRenewDismission()
    {
        return $this->container['days_renew_dismission'];
    }

    /**
     * Sets days_renew_dismission
     *
     * @param int|null $days_renew_dismission days_renew_dismission
     *
     * @return self
     */
    public function setDaysRenewDismission($days_renew_dismission)
    {
        if (is_null($days_renew_dismission)) {
            array_push($this->openAPINullablesSetToNull, 'days_renew_dismission');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_renew_dismission', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_renew_dismission'] = $days_renew_dismission;

        return $this;
    }

    /**
     * Gets days_no_secondary
     *
     * @return int|null
     */
    public function getDaysNoSecondary()
    {
        return $this->container['days_no_secondary'];
    }

    /**
     * Sets days_no_secondary
     *
     * @param int|null $days_no_secondary days_no_secondary
     *
     * @return self
     */
    public function setDaysNoSecondary($days_no_secondary)
    {
        if (is_null($days_no_secondary)) {
            array_push($this->openAPINullablesSetToNull, 'days_no_secondary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_no_secondary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_no_secondary'] = $days_no_secondary;

        return $this;
    }

    /**
     * Gets days_no_service_change
     *
     * @return int|null
     */
    public function getDaysNoServiceChange()
    {
        return $this->container['days_no_service_change'];
    }

    /**
     * Sets days_no_service_change
     *
     * @param int|null $days_no_service_change days_no_service_change
     *
     * @return self
     */
    public function setDaysNoServiceChange($days_no_service_change)
    {
        if (is_null($days_no_service_change)) {
            array_push($this->openAPINullablesSetToNull, 'days_no_service_change');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_no_service_change', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_no_service_change'] = $days_no_service_change;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


