<?php
/**
 * SecuremailStatistics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * SecuremailStatistics Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SecuremailStatistics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SecuremailStatistics';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'quantity' => 'int',
        'protected_mailboxes' => 'int',
        'not_protected_mailboxes' => 'int',
        'weekly_elaborated_messages' => 'int',
        'weekly_spam_messages' => 'int',
        'weekly_blocked_spam_percentage' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'quantity' => null,
        'protected_mailboxes' => null,
        'not_protected_mailboxes' => null,
        'weekly_elaborated_messages' => null,
        'weekly_spam_messages' => null,
        'weekly_blocked_spam_percentage' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'quantity' => false,
        'protected_mailboxes' => false,
        'not_protected_mailboxes' => false,
        'weekly_elaborated_messages' => false,
        'weekly_spam_messages' => false,
        'weekly_blocked_spam_percentage' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'quantity' => 'quantity',
        'protected_mailboxes' => 'protected_mailboxes',
        'not_protected_mailboxes' => 'not_protected_mailboxes',
        'weekly_elaborated_messages' => 'weekly_elaborated_messages',
        'weekly_spam_messages' => 'weekly_spam_messages',
        'weekly_blocked_spam_percentage' => 'weekly_blocked_spam_percentage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'quantity' => 'setQuantity',
        'protected_mailboxes' => 'setProtectedMailboxes',
        'not_protected_mailboxes' => 'setNotProtectedMailboxes',
        'weekly_elaborated_messages' => 'setWeeklyElaboratedMessages',
        'weekly_spam_messages' => 'setWeeklySpamMessages',
        'weekly_blocked_spam_percentage' => 'setWeeklyBlockedSpamPercentage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'quantity' => 'getQuantity',
        'protected_mailboxes' => 'getProtectedMailboxes',
        'not_protected_mailboxes' => 'getNotProtectedMailboxes',
        'weekly_elaborated_messages' => 'getWeeklyElaboratedMessages',
        'weekly_spam_messages' => 'getWeeklySpamMessages',
        'weekly_blocked_spam_percentage' => 'getWeeklyBlockedSpamPercentage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('protected_mailboxes', $data ?? [], null);
        $this->setIfExists('not_protected_mailboxes', $data ?? [], null);
        $this->setIfExists('weekly_elaborated_messages', $data ?? [], null);
        $this->setIfExists('weekly_spam_messages', $data ?? [], null);
        $this->setIfExists('weekly_blocked_spam_percentage', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets quantity
     *
     * @return int|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets protected_mailboxes
     *
     * @return int|null
     */
    public function getProtectedMailboxes()
    {
        return $this->container['protected_mailboxes'];
    }

    /**
     * Sets protected_mailboxes
     *
     * @param int|null $protected_mailboxes protected_mailboxes
     *
     * @return self
     */
    public function setProtectedMailboxes($protected_mailboxes)
    {
        if (is_null($protected_mailboxes)) {
            throw new \InvalidArgumentException('non-nullable protected_mailboxes cannot be null');
        }
        $this->container['protected_mailboxes'] = $protected_mailboxes;

        return $this;
    }

    /**
     * Gets not_protected_mailboxes
     *
     * @return int|null
     */
    public function getNotProtectedMailboxes()
    {
        return $this->container['not_protected_mailboxes'];
    }

    /**
     * Sets not_protected_mailboxes
     *
     * @param int|null $not_protected_mailboxes not_protected_mailboxes
     *
     * @return self
     */
    public function setNotProtectedMailboxes($not_protected_mailboxes)
    {
        if (is_null($not_protected_mailboxes)) {
            throw new \InvalidArgumentException('non-nullable not_protected_mailboxes cannot be null');
        }
        $this->container['not_protected_mailboxes'] = $not_protected_mailboxes;

        return $this;
    }

    /**
     * Gets weekly_elaborated_messages
     *
     * @return int|null
     */
    public function getWeeklyElaboratedMessages()
    {
        return $this->container['weekly_elaborated_messages'];
    }

    /**
     * Sets weekly_elaborated_messages
     *
     * @param int|null $weekly_elaborated_messages weekly_elaborated_messages
     *
     * @return self
     */
    public function setWeeklyElaboratedMessages($weekly_elaborated_messages)
    {
        if (is_null($weekly_elaborated_messages)) {
            throw new \InvalidArgumentException('non-nullable weekly_elaborated_messages cannot be null');
        }
        $this->container['weekly_elaborated_messages'] = $weekly_elaborated_messages;

        return $this;
    }

    /**
     * Gets weekly_spam_messages
     *
     * @return int|null
     */
    public function getWeeklySpamMessages()
    {
        return $this->container['weekly_spam_messages'];
    }

    /**
     * Sets weekly_spam_messages
     *
     * @param int|null $weekly_spam_messages weekly_spam_messages
     *
     * @return self
     */
    public function setWeeklySpamMessages($weekly_spam_messages)
    {
        if (is_null($weekly_spam_messages)) {
            throw new \InvalidArgumentException('non-nullable weekly_spam_messages cannot be null');
        }
        $this->container['weekly_spam_messages'] = $weekly_spam_messages;

        return $this;
    }

    /**
     * Gets weekly_blocked_spam_percentage
     *
     * @return int|null
     */
    public function getWeeklyBlockedSpamPercentage()
    {
        return $this->container['weekly_blocked_spam_percentage'];
    }

    /**
     * Sets weekly_blocked_spam_percentage
     *
     * @param int|null $weekly_blocked_spam_percentage weekly_blocked_spam_percentage
     *
     * @return self
     */
    public function setWeeklyBlockedSpamPercentage($weekly_blocked_spam_percentage)
    {
        if (is_null($weekly_blocked_spam_percentage)) {
            throw new \InvalidArgumentException('non-nullable weekly_blocked_spam_percentage cannot be null');
        }
        $this->container['weekly_blocked_spam_percentage'] = $weekly_blocked_spam_percentage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


