<?php
/**
 * SslCertificate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Shellrent
 *
 * API REST per gestire in modo automatico i servizi del proprio account Shellrent: domini, hosting, server, storage, certificati SSL, acquisti e fatturazione. L'accesso avviene tramite OAuth2 (client credentials) con scope specifici per area.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shellrent\Sdk\Model;

use \ArrayAccess;
use \Shellrent\Sdk\ObjectSerializer;

/**
 * SslCertificate Class Doc Comment
 *
 * @category Class
 * @package  Shellrent\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SslCertificate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SslCertificate';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ssl_certificate_id' => 'int',
        'purchase_id' => 'int',
        'domain_name' => 'string',
        'cn_type' => 'string',
        'validation_type' => 'string',
        'san_max' => 'int',
        'can_reissue' => 'bool',
        'validation_method' => 'string',
        'valid_to' => '\DateTime',
        'csr_md5_hash' => 'string',
        'csr_sha256_hash' => 'string',
        'certificate_status' => 'string',
        'approver_email' => 'string',
        'admin_first_name' => 'string',
        'admin_last_name' => 'string',
        'admin_organization' => 'string',
        'admin_role' => 'string',
        'admin_email' => 'string',
        'admin_phone_cc' => 'string',
        'admin_phone_number' => 'string',
        'admin_address' => 'string',
        'admin_city' => 'string',
        'admin_state' => 'string',
        'admin_postal_code' => 'string',
        'admin_country' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ssl_certificate_id' => null,
        'purchase_id' => null,
        'domain_name' => null,
        'cn_type' => null,
        'validation_type' => null,
        'san_max' => null,
        'can_reissue' => null,
        'validation_method' => null,
        'valid_to' => 'date-time',
        'csr_md5_hash' => null,
        'csr_sha256_hash' => null,
        'certificate_status' => null,
        'approver_email' => 'email',
        'admin_first_name' => null,
        'admin_last_name' => null,
        'admin_organization' => null,
        'admin_role' => null,
        'admin_email' => 'email',
        'admin_phone_cc' => null,
        'admin_phone_number' => null,
        'admin_address' => null,
        'admin_city' => null,
        'admin_state' => null,
        'admin_postal_code' => null,
        'admin_country' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ssl_certificate_id' => false,
        'purchase_id' => false,
        'domain_name' => true,
        'cn_type' => true,
        'validation_type' => true,
        'san_max' => false,
        'can_reissue' => false,
        'validation_method' => true,
        'valid_to' => true,
        'csr_md5_hash' => true,
        'csr_sha256_hash' => true,
        'certificate_status' => true,
        'approver_email' => true,
        'admin_first_name' => true,
        'admin_last_name' => true,
        'admin_organization' => true,
        'admin_role' => true,
        'admin_email' => true,
        'admin_phone_cc' => true,
        'admin_phone_number' => true,
        'admin_address' => true,
        'admin_city' => true,
        'admin_state' => true,
        'admin_postal_code' => true,
        'admin_country' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ssl_certificate_id' => 'ssl_certificate_id',
        'purchase_id' => 'purchase_id',
        'domain_name' => 'domain_name',
        'cn_type' => 'cn_type',
        'validation_type' => 'validation_type',
        'san_max' => 'san_max',
        'can_reissue' => 'can_reissue',
        'validation_method' => 'validation_method',
        'valid_to' => 'valid_to',
        'csr_md5_hash' => 'csr_md5_hash',
        'csr_sha256_hash' => 'csr_sha256_hash',
        'certificate_status' => 'certificate_status',
        'approver_email' => 'approver_email',
        'admin_first_name' => 'admin_first_name',
        'admin_last_name' => 'admin_last_name',
        'admin_organization' => 'admin_organization',
        'admin_role' => 'admin_role',
        'admin_email' => 'admin_email',
        'admin_phone_cc' => 'admin_phone_cc',
        'admin_phone_number' => 'admin_phone_number',
        'admin_address' => 'admin_address',
        'admin_city' => 'admin_city',
        'admin_state' => 'admin_state',
        'admin_postal_code' => 'admin_postal_code',
        'admin_country' => 'admin_country'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ssl_certificate_id' => 'setSslCertificateId',
        'purchase_id' => 'setPurchaseId',
        'domain_name' => 'setDomainName',
        'cn_type' => 'setCnType',
        'validation_type' => 'setValidationType',
        'san_max' => 'setSanMax',
        'can_reissue' => 'setCanReissue',
        'validation_method' => 'setValidationMethod',
        'valid_to' => 'setValidTo',
        'csr_md5_hash' => 'setCsrMd5Hash',
        'csr_sha256_hash' => 'setCsrSha256Hash',
        'certificate_status' => 'setCertificateStatus',
        'approver_email' => 'setApproverEmail',
        'admin_first_name' => 'setAdminFirstName',
        'admin_last_name' => 'setAdminLastName',
        'admin_organization' => 'setAdminOrganization',
        'admin_role' => 'setAdminRole',
        'admin_email' => 'setAdminEmail',
        'admin_phone_cc' => 'setAdminPhoneCc',
        'admin_phone_number' => 'setAdminPhoneNumber',
        'admin_address' => 'setAdminAddress',
        'admin_city' => 'setAdminCity',
        'admin_state' => 'setAdminState',
        'admin_postal_code' => 'setAdminPostalCode',
        'admin_country' => 'setAdminCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ssl_certificate_id' => 'getSslCertificateId',
        'purchase_id' => 'getPurchaseId',
        'domain_name' => 'getDomainName',
        'cn_type' => 'getCnType',
        'validation_type' => 'getValidationType',
        'san_max' => 'getSanMax',
        'can_reissue' => 'getCanReissue',
        'validation_method' => 'getValidationMethod',
        'valid_to' => 'getValidTo',
        'csr_md5_hash' => 'getCsrMd5Hash',
        'csr_sha256_hash' => 'getCsrSha256Hash',
        'certificate_status' => 'getCertificateStatus',
        'approver_email' => 'getApproverEmail',
        'admin_first_name' => 'getAdminFirstName',
        'admin_last_name' => 'getAdminLastName',
        'admin_organization' => 'getAdminOrganization',
        'admin_role' => 'getAdminRole',
        'admin_email' => 'getAdminEmail',
        'admin_phone_cc' => 'getAdminPhoneCc',
        'admin_phone_number' => 'getAdminPhoneNumber',
        'admin_address' => 'getAdminAddress',
        'admin_city' => 'getAdminCity',
        'admin_state' => 'getAdminState',
        'admin_postal_code' => 'getAdminPostalCode',
        'admin_country' => 'getAdminCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ssl_certificate_id', $data ?? [], null);
        $this->setIfExists('purchase_id', $data ?? [], null);
        $this->setIfExists('domain_name', $data ?? [], null);
        $this->setIfExists('cn_type', $data ?? [], null);
        $this->setIfExists('validation_type', $data ?? [], null);
        $this->setIfExists('san_max', $data ?? [], null);
        $this->setIfExists('can_reissue', $data ?? [], null);
        $this->setIfExists('validation_method', $data ?? [], null);
        $this->setIfExists('valid_to', $data ?? [], null);
        $this->setIfExists('csr_md5_hash', $data ?? [], null);
        $this->setIfExists('csr_sha256_hash', $data ?? [], null);
        $this->setIfExists('certificate_status', $data ?? [], null);
        $this->setIfExists('approver_email', $data ?? [], null);
        $this->setIfExists('admin_first_name', $data ?? [], null);
        $this->setIfExists('admin_last_name', $data ?? [], null);
        $this->setIfExists('admin_organization', $data ?? [], null);
        $this->setIfExists('admin_role', $data ?? [], null);
        $this->setIfExists('admin_email', $data ?? [], null);
        $this->setIfExists('admin_phone_cc', $data ?? [], null);
        $this->setIfExists('admin_phone_number', $data ?? [], null);
        $this->setIfExists('admin_address', $data ?? [], null);
        $this->setIfExists('admin_city', $data ?? [], null);
        $this->setIfExists('admin_state', $data ?? [], null);
        $this->setIfExists('admin_postal_code', $data ?? [], null);
        $this->setIfExists('admin_country', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ssl_certificate_id
     *
     * @return int|null
     */
    public function getSslCertificateId()
    {
        return $this->container['ssl_certificate_id'];
    }

    /**
     * Sets ssl_certificate_id
     *
     * @param int|null $ssl_certificate_id ssl_certificate_id
     *
     * @return self
     */
    public function setSslCertificateId($ssl_certificate_id)
    {
        if (is_null($ssl_certificate_id)) {
            throw new \InvalidArgumentException('non-nullable ssl_certificate_id cannot be null');
        }
        $this->container['ssl_certificate_id'] = $ssl_certificate_id;

        return $this;
    }

    /**
     * Gets purchase_id
     *
     * @return int|null
     */
    public function getPurchaseId()
    {
        return $this->container['purchase_id'];
    }

    /**
     * Sets purchase_id
     *
     * @param int|null $purchase_id purchase_id
     *
     * @return self
     */
    public function setPurchaseId($purchase_id)
    {
        if (is_null($purchase_id)) {
            throw new \InvalidArgumentException('non-nullable purchase_id cannot be null');
        }
        $this->container['purchase_id'] = $purchase_id;

        return $this;
    }

    /**
     * Gets domain_name
     *
     * @return string|null
     */
    public function getDomainName()
    {
        return $this->container['domain_name'];
    }

    /**
     * Sets domain_name
     *
     * @param string|null $domain_name domain_name
     *
     * @return self
     */
    public function setDomainName($domain_name)
    {
        if (is_null($domain_name)) {
            array_push($this->openAPINullablesSetToNull, 'domain_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain_name'] = $domain_name;

        return $this;
    }

    /**
     * Gets cn_type
     *
     * @return string|null
     */
    public function getCnType()
    {
        return $this->container['cn_type'];
    }

    /**
     * Sets cn_type
     *
     * @param string|null $cn_type cn_type
     *
     * @return self
     */
    public function setCnType($cn_type)
    {
        if (is_null($cn_type)) {
            array_push($this->openAPINullablesSetToNull, 'cn_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cn_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cn_type'] = $cn_type;

        return $this;
    }

    /**
     * Gets validation_type
     *
     * @return string|null
     */
    public function getValidationType()
    {
        return $this->container['validation_type'];
    }

    /**
     * Sets validation_type
     *
     * @param string|null $validation_type validation_type
     *
     * @return self
     */
    public function setValidationType($validation_type)
    {
        if (is_null($validation_type)) {
            array_push($this->openAPINullablesSetToNull, 'validation_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_type'] = $validation_type;

        return $this;
    }

    /**
     * Gets san_max
     *
     * @return int|null
     */
    public function getSanMax()
    {
        return $this->container['san_max'];
    }

    /**
     * Sets san_max
     *
     * @param int|null $san_max san_max
     *
     * @return self
     */
    public function setSanMax($san_max)
    {
        if (is_null($san_max)) {
            throw new \InvalidArgumentException('non-nullable san_max cannot be null');
        }
        $this->container['san_max'] = $san_max;

        return $this;
    }

    /**
     * Gets can_reissue
     *
     * @return bool|null
     */
    public function getCanReissue()
    {
        return $this->container['can_reissue'];
    }

    /**
     * Sets can_reissue
     *
     * @param bool|null $can_reissue can_reissue
     *
     * @return self
     */
    public function setCanReissue($can_reissue)
    {
        if (is_null($can_reissue)) {
            throw new \InvalidArgumentException('non-nullable can_reissue cannot be null');
        }
        $this->container['can_reissue'] = $can_reissue;

        return $this;
    }

    /**
     * Gets validation_method
     *
     * @return string|null
     */
    public function getValidationMethod()
    {
        return $this->container['validation_method'];
    }

    /**
     * Sets validation_method
     *
     * @param string|null $validation_method validation_method
     *
     * @return self
     */
    public function setValidationMethod($validation_method)
    {
        if (is_null($validation_method)) {
            array_push($this->openAPINullablesSetToNull, 'validation_method');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_method', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_method'] = $validation_method;

        return $this;
    }

    /**
     * Gets valid_to
     *
     * @return \DateTime|null
     */
    public function getValidTo()
    {
        return $this->container['valid_to'];
    }

    /**
     * Sets valid_to
     *
     * @param \DateTime|null $valid_to valid_to
     *
     * @return self
     */
    public function setValidTo($valid_to)
    {
        if (is_null($valid_to)) {
            array_push($this->openAPINullablesSetToNull, 'valid_to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valid_to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valid_to'] = $valid_to;

        return $this;
    }

    /**
     * Gets csr_md5_hash
     *
     * @return string|null
     */
    public function getCsrMd5Hash()
    {
        return $this->container['csr_md5_hash'];
    }

    /**
     * Sets csr_md5_hash
     *
     * @param string|null $csr_md5_hash csr_md5_hash
     *
     * @return self
     */
    public function setCsrMd5Hash($csr_md5_hash)
    {
        if (is_null($csr_md5_hash)) {
            array_push($this->openAPINullablesSetToNull, 'csr_md5_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csr_md5_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csr_md5_hash'] = $csr_md5_hash;

        return $this;
    }

    /**
     * Gets csr_sha256_hash
     *
     * @return string|null
     */
    public function getCsrSha256Hash()
    {
        return $this->container['csr_sha256_hash'];
    }

    /**
     * Sets csr_sha256_hash
     *
     * @param string|null $csr_sha256_hash csr_sha256_hash
     *
     * @return self
     */
    public function setCsrSha256Hash($csr_sha256_hash)
    {
        if (is_null($csr_sha256_hash)) {
            array_push($this->openAPINullablesSetToNull, 'csr_sha256_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csr_sha256_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csr_sha256_hash'] = $csr_sha256_hash;

        return $this;
    }

    /**
     * Gets certificate_status
     *
     * @return string|null
     */
    public function getCertificateStatus()
    {
        return $this->container['certificate_status'];
    }

    /**
     * Sets certificate_status
     *
     * @param string|null $certificate_status certificate_status
     *
     * @return self
     */
    public function setCertificateStatus($certificate_status)
    {
        if (is_null($certificate_status)) {
            array_push($this->openAPINullablesSetToNull, 'certificate_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('certificate_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['certificate_status'] = $certificate_status;

        return $this;
    }

    /**
     * Gets approver_email
     *
     * @return string|null
     */
    public function getApproverEmail()
    {
        return $this->container['approver_email'];
    }

    /**
     * Sets approver_email
     *
     * @param string|null $approver_email approver_email
     *
     * @return self
     */
    public function setApproverEmail($approver_email)
    {
        if (is_null($approver_email)) {
            array_push($this->openAPINullablesSetToNull, 'approver_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('approver_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['approver_email'] = $approver_email;

        return $this;
    }

    /**
     * Gets admin_first_name
     *
     * @return string|null
     */
    public function getAdminFirstName()
    {
        return $this->container['admin_first_name'];
    }

    /**
     * Sets admin_first_name
     *
     * @param string|null $admin_first_name admin_first_name
     *
     * @return self
     */
    public function setAdminFirstName($admin_first_name)
    {
        if (is_null($admin_first_name)) {
            array_push($this->openAPINullablesSetToNull, 'admin_first_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_first_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_first_name'] = $admin_first_name;

        return $this;
    }

    /**
     * Gets admin_last_name
     *
     * @return string|null
     */
    public function getAdminLastName()
    {
        return $this->container['admin_last_name'];
    }

    /**
     * Sets admin_last_name
     *
     * @param string|null $admin_last_name admin_last_name
     *
     * @return self
     */
    public function setAdminLastName($admin_last_name)
    {
        if (is_null($admin_last_name)) {
            array_push($this->openAPINullablesSetToNull, 'admin_last_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_last_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_last_name'] = $admin_last_name;

        return $this;
    }

    /**
     * Gets admin_organization
     *
     * @return string|null
     */
    public function getAdminOrganization()
    {
        return $this->container['admin_organization'];
    }

    /**
     * Sets admin_organization
     *
     * @param string|null $admin_organization admin_organization
     *
     * @return self
     */
    public function setAdminOrganization($admin_organization)
    {
        if (is_null($admin_organization)) {
            array_push($this->openAPINullablesSetToNull, 'admin_organization');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_organization', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_organization'] = $admin_organization;

        return $this;
    }

    /**
     * Gets admin_role
     *
     * @return string|null
     */
    public function getAdminRole()
    {
        return $this->container['admin_role'];
    }

    /**
     * Sets admin_role
     *
     * @param string|null $admin_role admin_role
     *
     * @return self
     */
    public function setAdminRole($admin_role)
    {
        if (is_null($admin_role)) {
            array_push($this->openAPINullablesSetToNull, 'admin_role');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_role', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_role'] = $admin_role;

        return $this;
    }

    /**
     * Gets admin_email
     *
     * @return string|null
     */
    public function getAdminEmail()
    {
        return $this->container['admin_email'];
    }

    /**
     * Sets admin_email
     *
     * @param string|null $admin_email admin_email
     *
     * @return self
     */
    public function setAdminEmail($admin_email)
    {
        if (is_null($admin_email)) {
            array_push($this->openAPINullablesSetToNull, 'admin_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_email'] = $admin_email;

        return $this;
    }

    /**
     * Gets admin_phone_cc
     *
     * @return string|null
     */
    public function getAdminPhoneCc()
    {
        return $this->container['admin_phone_cc'];
    }

    /**
     * Sets admin_phone_cc
     *
     * @param string|null $admin_phone_cc admin_phone_cc
     *
     * @return self
     */
    public function setAdminPhoneCc($admin_phone_cc)
    {
        if (is_null($admin_phone_cc)) {
            array_push($this->openAPINullablesSetToNull, 'admin_phone_cc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_phone_cc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_phone_cc'] = $admin_phone_cc;

        return $this;
    }

    /**
     * Gets admin_phone_number
     *
     * @return string|null
     */
    public function getAdminPhoneNumber()
    {
        return $this->container['admin_phone_number'];
    }

    /**
     * Sets admin_phone_number
     *
     * @param string|null $admin_phone_number admin_phone_number
     *
     * @return self
     */
    public function setAdminPhoneNumber($admin_phone_number)
    {
        if (is_null($admin_phone_number)) {
            array_push($this->openAPINullablesSetToNull, 'admin_phone_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_phone_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_phone_number'] = $admin_phone_number;

        return $this;
    }

    /**
     * Gets admin_address
     *
     * @return string|null
     */
    public function getAdminAddress()
    {
        return $this->container['admin_address'];
    }

    /**
     * Sets admin_address
     *
     * @param string|null $admin_address admin_address
     *
     * @return self
     */
    public function setAdminAddress($admin_address)
    {
        if (is_null($admin_address)) {
            array_push($this->openAPINullablesSetToNull, 'admin_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_address'] = $admin_address;

        return $this;
    }

    /**
     * Gets admin_city
     *
     * @return string|null
     */
    public function getAdminCity()
    {
        return $this->container['admin_city'];
    }

    /**
     * Sets admin_city
     *
     * @param string|null $admin_city admin_city
     *
     * @return self
     */
    public function setAdminCity($admin_city)
    {
        if (is_null($admin_city)) {
            array_push($this->openAPINullablesSetToNull, 'admin_city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_city'] = $admin_city;

        return $this;
    }

    /**
     * Gets admin_state
     *
     * @return string|null
     */
    public function getAdminState()
    {
        return $this->container['admin_state'];
    }

    /**
     * Sets admin_state
     *
     * @param string|null $admin_state admin_state
     *
     * @return self
     */
    public function setAdminState($admin_state)
    {
        if (is_null($admin_state)) {
            array_push($this->openAPINullablesSetToNull, 'admin_state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_state'] = $admin_state;

        return $this;
    }

    /**
     * Gets admin_postal_code
     *
     * @return string|null
     */
    public function getAdminPostalCode()
    {
        return $this->container['admin_postal_code'];
    }

    /**
     * Sets admin_postal_code
     *
     * @param string|null $admin_postal_code admin_postal_code
     *
     * @return self
     */
    public function setAdminPostalCode($admin_postal_code)
    {
        if (is_null($admin_postal_code)) {
            array_push($this->openAPINullablesSetToNull, 'admin_postal_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_postal_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_postal_code'] = $admin_postal_code;

        return $this;
    }

    /**
     * Gets admin_country
     *
     * @return string|null
     */
    public function getAdminCountry()
    {
        return $this->container['admin_country'];
    }

    /**
     * Sets admin_country
     *
     * @param string|null $admin_country admin_country
     *
     * @return self
     */
    public function setAdminCountry($admin_country)
    {
        if (is_null($admin_country)) {
            array_push($this->openAPINullablesSetToNull, 'admin_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admin_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admin_country'] = $admin_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


